# Generated by Django 4.2.20 on 2025-06-07 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("viewer", "Viewer"),
                        ],
                        default="user",
                        help_text="User's role in this workspace",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this workspace assignment is active",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace User",
                "verbose_name_plural": "Workspace Users",
                "unique_together": {("user", "workspace")},
            },
        ),
        migrations.AddField(
            model_name="useraccount",
            name="workspaces",
            field=models.ManyToManyField(
                blank=True,
                help_text="Workspaces this user has access to",
                related_name="users",
                through="users.WorkspaceUser",
                to="master_data.workspace",
            ),
        ),
    ]
