# Generated by Django 4.2.17 on 2025-08-26 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_invitation_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invitor",
            field=models.ForeignKey(
                help_text="User who sent this invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
