# Generated by Django 4.2.17 on 2025-08-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_fix_user_deletion_constraints"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_userinvitation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
