CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "master_data_field" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "name" varchar(30) NOT NULL, "field_level" smallint NOT NULL, "next_field_id" bigint NULL REFERENCES "master_data_field" ("id") DEFERRABLE INITIALLY DEFERRED, "platform_id" bigint NOT NULL REFERENCES "master_data_platform" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "master_data_field_platform_id_name_field_level_ec2a0933_uniq" ON "master_data_field" ("platform_id", "name", "field_level");
CREATE INDEX "master_data_field_next_field_id_028c5d89" ON "master_data_field" ("next_field_id");
CREATE INDEX "master_data_field_platform_id_1dfa112d" ON "master_data_field" ("platform_id");
CREATE TABLE IF NOT EXISTS "master_data_platform" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "platform_type" varchar(30) NOT NULL, "name" varchar(30) NOT NULL);
CREATE TABLE IF NOT EXISTS "master_data_dimensionvalue" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "valid_from" date NULL, "definition" text NULL, "dimension_value" varchar(30) NOT NULL, "valid_until" date NULL, "dimension_value_label" varchar(50) NOT NULL, "dimension_value_utm" varchar(30) NOT NULL, "dimension_id" bigint NOT NULL REFERENCES "master_data_dimension" ("id") DEFERRABLE INITIALLY DEFERRED, "parent_id" bigint NULL REFERENCES "master_data_dimensionvalue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "master_data_dimensionvalue_dimension_id_dimension_value_31b1f3d6_uniq" ON "master_data_dimensionvalue" ("dimension_id", "dimension_value");
CREATE INDEX "master_data_dimensionvalue_dimension_id_56f46ab9" ON "master_data_dimensionvalue" ("dimension_id");
CREATE INDEX "master_data_dimensionvalue_parent_id_6a07b214" ON "master_data_dimensionvalue" ("parent_id");
CREATE TABLE IF NOT EXISTS "master_data_workspace" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "name" varchar(30) NOT NULL UNIQUE, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "logo" varchar(100) NULL, "status" varchar(30) NOT NULL);
CREATE INDEX "master_data_workspace_created_by_id_48e51333" ON "master_data_workspace" ("created_by_id");
CREATE TABLE IF NOT EXISTS "master_data_dimension" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "definition" text NULL, "dimension_type" varchar(30) NOT NULL, "name" varchar(30) NOT NULL UNIQUE, "status" varchar(30) NOT NULL, "parent_id" bigint NULL REFERENCES "master_data_dimension" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "master_data_dimension_parent_id_366b2d7e" ON "master_data_dimension" ("parent_id");
CREATE TABLE IF NOT EXISTS "master_data_ruledetail" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "prefix" varchar(20) NULL, "suffix" varchar(20) NULL, "delimiter" varchar(1) NULL, "dimension_order" smallint NOT NULL, "dimension_id" bigint NOT NULL REFERENCES "master_data_dimension" ("id") DEFERRABLE INITIALLY DEFERRED, "rule_id" bigint NOT NULL REFERENCES "master_data_rule" ("id") DEFERRABLE INITIALLY DEFERRED, "field_id" bigint NOT NULL REFERENCES "master_data_field" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "master_data_ruledetail_dimension_id_2ea66512" ON "master_data_ruledetail" ("dimension_id");
CREATE INDEX "master_data_ruledetail_rule_id_a5c2ff1d" ON "master_data_ruledetail" ("rule_id");
CREATE INDEX "master_data_ruledetail_field_id_efa0cce0" ON "master_data_ruledetail" ("field_id");
CREATE TABLE IF NOT EXISTS "master_data_rule" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "name" varchar(50) NOT NULL, "status" varchar(30) NOT NULL, "platform_id" bigint NOT NULL REFERENCES "master_data_platform" ("id") DEFERRABLE INITIALLY DEFERRED, "description" text NULL);
CREATE INDEX "master_data_rule_platform_id_c2860211" ON "master_data_rule" ("platform_id");
CREATE TABLE IF NOT EXISTS "master_data_string" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "last_updated" datetime NOT NULL, "created" datetime NOT NULL, "field_id" bigint NOT NULL REFERENCES "master_data_field" ("id") DEFERRABLE INITIALLY DEFERRED, "string_uuid" char(32) NOT NULL, "parent_uuid" char(32) NULL, "value" varchar(400) NOT NULL, "submission_id" bigint NOT NULL REFERENCES "master_data_submission" ("id") DEFERRABLE INITIALLY DEFERRED, "parent_id" bigint NULL REFERENCES "master_data_string" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "master_data_string_field_id_b56d8e4a" ON "master_data_string" ("field_id");
CREATE INDEX "master_data_string_submission_id_221ba67a" ON "master_data_string" ("submission_id");
CREATE INDEX "master_data_string_parent_id_1ee0d17a" ON "master_data_string" ("parent_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE UNIQUE INDEX "master_data_ruledetail_rule_id_field_id_dimension_id_dimension_order_217c2676_uniq" ON "master_data_ruledetail" ("rule_id", "field_id", "dimension_id", "dimension_order");
CREATE TABLE IF NOT EXISTS "master_data_submission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "name" varchar(30) NOT NULL, "description" text NULL, "status" varchar(30) NOT NULL, "rule_id" bigint NOT NULL REFERENCES "master_data_rule" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "master_data_submission_rule_id_1e526e04" ON "master_data_submission" ("rule_id");
CREATE TABLE IF NOT EXISTS "master_data_stringdetail" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created" datetime NOT NULL, "last_updated" datetime NOT NULL, "dimension_value_freetext" varchar(100) NULL, "string_id" bigint NOT NULL REFERENCES "master_data_string" ("id") DEFERRABLE INITIALLY DEFERRED, "dimension_id" bigint NOT NULL REFERENCES "master_data_dimension" ("id") DEFERRABLE INITIALLY DEFERRED, "dimension_value_id" bigint NULL REFERENCES "master_data_dimensionvalue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "master_data_stringdetail_string_id_a7e3fdd3" ON "master_data_stringdetail" ("string_id");
CREATE INDEX "master_data_stringdetail_dimension_id_8bd2b7c6" ON "master_data_stringdetail" ("dimension_id");
CREATE INDEX "master_data_stringdetail_dimension_value_id_92062523" ON "master_data_stringdetail" ("dimension_value_id");
