# Generated by Django 4.2.20 on 2025-06-02 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import master_data.models.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this dimension",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this dimension represents",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("list", "List"), ("text", "Free Text")],
                        default="list",
                        help_text="Type of dimension: list of values or free text",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this dimension",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent dimension if this is a sub-dimension",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_dimensions",
                        to="master_data.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension",
                "verbose_name_plural": "Dimensions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The actual value (e.g., 'prod', 'dev')",
                        max_length=30,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label for this value", max_length=50
                    ),
                ),
                (
                    "utm",
                    models.CharField(
                        help_text="UTM or tracking code for this value", max_length=30
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this value represents",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Date from which this value is valid",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date until which this value is valid",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="The dimension this value belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension_values",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent value if this is a sub-value",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_dimension_values",
                        to="master_data.dimensionvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension Value",
                "verbose_name_plural": "Dimension Values",
                "ordering": ["dimension", "value"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this field (e.g., 'environment', 'project')",
                        max_length=30,
                    ),
                ),
                (
                    "field_level",
                    models.SmallIntegerField(
                        help_text="Hierarchical level of this field (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "next_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="Next field in the hierarchy sequence",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_fields",
                        to="master_data.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ["platform", "field_level"],
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "platform_type",
                    models.CharField(
                        help_text="Type or category of this platform", max_length=30
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the platform", max_length=30
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for this platform",
                        unique=True,
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the icon to display for this platform",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this naming rule", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this rule generates",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this rule",
                        max_length=30,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default rule for the platform",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Platform this rule applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="master_data.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
                "ordering": ["platform", "name"],
            },
        ),
        migrations.CreateModel(
            name="String",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Generated string value following naming convention",
                        max_length=400,
                    ),
                ),
                (
                    "string_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this string",
                        unique=True,
                    ),
                ),
                (
                    "parent_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of parent string for hierarchical linking",
                        null=True,
                    ),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this string was automatically generated",
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata about how this string was generated",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field this string belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_strings",
                        to="master_data.field",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent string in hierarchical naming structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_strings",
                        to="master_data.string",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        editable=False,
                        help_text="Rule used to generate this string (auto-set from submission)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_strings",
                        to="master_data.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "String",
                "verbose_name_plural": "Strings",
                "ordering": ["field__field_level", "value"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this workspace",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default=master_data.models.base.default_workspace_logo,
                        help_text="Logo image for this workspace",
                        null=True,
                        upload_to="workspaces/logos/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this workspace",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this submission", max_length=30
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this submission",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Current status of this submission",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="The naming rule to apply for this submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="master_data.rule",
                    ),
                ),
                (
                    "selected_parent_string",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent string to base this submission on (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_parent_string",
                        to="master_data.string",
                    ),
                ),
                (
                    "starting_field",
                    models.ForeignKey(
                        help_text="The field to start the naming sequence from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_field",
                        to="master_data.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="string",
            name="submission",
            field=models.ForeignKey(
                help_text="Submission that generated this string",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_strings",
                to="master_data.submission",
            ),
        ),
        migrations.CreateModel(
            name="RuleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Text to prepend to the dimension value",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Text to append to the dimension value",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        blank=True,
                        default="-",
                        help_text="Character to separate this dimension from others",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "dimension_order",
                    models.SmallIntegerField(
                        help_text="Order of this dimension in the naming sequence (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this dimension is required for string generation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="Dimension this formatting applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_details",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field this formatting applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_details",
                        to="master_data.field",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="Rule this detail belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_details",
                        to="master_data.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Detail",
                "verbose_name_plural": "Rule Details",
                "ordering": ["rule", "field", "dimension_order"],
            },
        ),
        migrations.AddField(
            model_name="field",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this field belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="master_data.platform",
            ),
        ),
        migrations.CreateModel(
            name="StringDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "dimension_value_freetext",
                    models.CharField(
                        blank=True,
                        help_text="Free text value (for text-type dimensions)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="Dimension this value represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="string_details",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "dimension_value",
                    models.ForeignKey(
                        blank=True,
                        help_text="Predefined dimension value (for list-type dimensions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="string_details",
                        to="master_data.dimensionvalue",
                    ),
                ),
                (
                    "string",
                    models.ForeignKey(
                        help_text="String this detail belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="string_details",
                        to="master_data.string",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Detail",
                "verbose_name_plural": "String Details",
                "ordering": ["string", "dimension"],
                "unique_together": {("string", "dimension")},
            },
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["rule", "field"], name="master_data_rule_id_3e6327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["string_uuid"], name="master_data_string__f6b20b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(fields=["value"], name="master_data_value_62f6c7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="string", unique_together={("rule", "field", "value")},
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["rule", "field", "dimension_order"],
                name="master_data_rule_id_0753aa_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ruledetail",
            unique_together={("rule", "field", "dimension", "dimension_order")},
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["platform", "status"], name="master_data_platfor_288f6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["is_default"], name="master_data_is_defa_1b8562_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rule", unique_together={("platform", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="field", unique_together={("platform", "name", "field_level")},
        ),
        migrations.AlterUniqueTogether(
            name="dimensionvalue", unique_together={("dimension", "value")},
        ),
    ]
