# Generated by Django 4.2.20 on 2025-06-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0003_add_workspace_to_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="field",
            options={
                "ordering": ["platform", "field_level"],
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={
                "ordering": ["name"],
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
            },
        ),
        migrations.AlterUniqueTogether(
            name="field", unique_together={("platform", "name", "field_level")},
        ),
        migrations.AlterUniqueTogether(name="platform", unique_together={("slug",)},),
        migrations.RemoveField(model_name="field", name="workspace",),
        migrations.RemoveField(model_name="platform", name="workspace",),
    ]
