# Generated by Django 4.2.7 on 2025-11-10 16:57

from django.db import migrations, models
import master_data.models.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        help_text="Type of approval action",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment or reason", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this action was performed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval History",
                "verbose_name_plural": "Approval Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this dimension (unique per workspace)",
                        max_length=30,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this dimension represents",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("list", "List"), ("text", "Free Text")],
                        default="list",
                        help_text="Type of dimension: list of values or free text",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this dimension",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension",
                "verbose_name_plural": "Dimensions",
                "ordering": ["workspace", "name"],
            },
        ),
        migrations.CreateModel(
            name="DimensionConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("no_spaces", "No Spaces"),
                            ("lowercase", "Lowercase Only"),
                            ("uppercase", "Uppercase Only"),
                            ("no_special_chars", "No Special Characters"),
                            ("alphanumeric", "Alphanumeric Only"),
                            ("numeric", "Numeric Only"),
                            ("max_length", "Maximum Length"),
                            ("min_length", "Minimum Length"),
                            ("regex", "Regular Expression"),
                            ("starts_with", "Starts With"),
                            ("ends_with", "Ends With"),
                            ("allowed_chars", "Allowed Characters"),
                            ("no_uppercase", "No Uppercase"),
                            ("no_numbers", "No Numbers"),
                            ("url_safe", "URL Safe"),
                        ],
                        help_text="Type of constraint to apply",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Configuration value for constraints that need it (e.g., max_length, regex pattern)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Custom error message to display when constraint is violated",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which constraint is applied (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this constraint is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension Constraint",
                "verbose_name_plural": "Dimension Constraints",
                "ordering": ["dimension", "order"],
            },
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The actual value (e.g., 'prod', 'dev')",
                        max_length=30,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label for this value", max_length=50
                    ),
                ),
                (
                    "utm",
                    models.CharField(
                        help_text="UTM or tracking code for this value", max_length=30
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this value represents",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Date from which this value is valid",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date until which this value is valid",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension Value",
                "verbose_name_plural": "Dimension Values",
                "ordering": ["workspace", "dimension", "value"],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this entity (e.g., 'environment', 'project')",
                        max_length=30,
                    ),
                ),
                (
                    "entity_level",
                    models.SmallIntegerField(
                        help_text="Hierarchical level of this entity (1, 2, 3, etc.)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
                "ordering": ["platform", "entity_level"],
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "platform_type",
                    models.CharField(
                        help_text="Type or category of this platform", max_length=30
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the platform", max_length=30
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for this platform"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the icon to display for this platform",
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=30)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this project",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        help_text="Current status of this project",
                        max_length=30,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Approval status of this project",
                        max_length=30,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this project was approved",
                        null=True,
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this project was rejected",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["workspace", "-created"],
            },
        ),
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("project_created", "Project Created"),
                            ("member_assigned", "Member Assigned"),
                            ("member_unassigned", "Member Unassigned"),
                            ("strings_generated", "Strings Generated"),
                            ("status_changed", "Status Changed"),
                            ("project_updated", "Project Updated"),
                            ("submitted_for_approval", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        help_text="Type of activity",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the activity"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Activity",
                "verbose_name_plural": "Project Activities",
                "ordering": ["project", "-created"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        help_text="User's role in this project",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "ordering": ["project", "user"],
            },
        ),
        migrations.CreateModel(
            name="ProjectString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Generated string value following naming convention",
                        max_length=400,
                    ),
                ),
                (
                    "string_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this string (globally unique)",
                        unique=True,
                    ),
                ),
                (
                    "parent_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of parent string for hierarchical linking",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project String",
                "verbose_name_plural": "Project Strings",
                "ordering": ["workspace", "project", "entity__entity_level", "value"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStringDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "dimension_value_freetext",
                    models.CharField(
                        blank=True,
                        help_text="Free-text dimension value (for text-type dimensions)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_inherited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this value was inherited from parent string",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project String Detail",
                "verbose_name_plural": "Project String Details",
                "ordering": ["workspace", "string", "dimension"],
            },
        ),
        migrations.CreateModel(
            name="PropagationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("string_generation_error", "String Generation Error"),
                            ("database_error", "Database Error"),
                            ("validation_error", "Validation Error"),
                            ("circular_dependency", "Circular Dependency"),
                            ("conflict_error", "Conflict Error"),
                            ("permission_error", "Permission Error"),
                            ("timeout_error", "Timeout Error"),
                            ("unknown_error", "Unknown Error"),
                        ],
                        help_text="Type of error that occurred",
                        max_length=30,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(help_text="Human-readable error message"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable error code",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "stack_trace",
                    models.TextField(
                        blank=True, help_text="Full stack trace of the error", null=True
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data about the error",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this operation has been retried",
                    ),
                ),
                (
                    "is_retryable",
                    models.BooleanField(
                        default=False, help_text="Whether this error can be retried"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Whether this error has been resolved"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this error was resolved", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Propagation Error",
                "verbose_name_plural": "Propagation Errors",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PropagationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this propagation batch",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("partial_failure", "Partial Failure"),
                        ],
                        default="pending",
                        help_text="Current status of the propagation job",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job actually started processing",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job completed or failed",
                        null=True,
                    ),
                ),
                (
                    "total_strings",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of strings to be processed"
                    ),
                ),
                (
                    "processed_strings",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of strings successfully processed"
                    ),
                ),
                (
                    "failed_strings",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of strings that failed processing"
                    ),
                ),
                (
                    "max_depth",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum propagation depth configured for this job",
                    ),
                ),
                (
                    "processing_method",
                    models.CharField(
                        choices=[
                            ("synchronous", "Synchronous"),
                            ("background", "Background"),
                            ("chunked", "Chunked Processing"),
                        ],
                        default="synchronous",
                        help_text="Processing method used for this job",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the job configuration and execution",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if job failed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Propagation Job",
                "verbose_name_plural": "Propagation Jobs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PropagationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict, help_text="User-specific propagation settings"
                    ),
                ),
            ],
            options={
                "verbose_name": "Propagation Settings",
                "verbose_name_plural": "Propagation Settings",
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this naming rule", max_length=50
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this rule generates",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this rule",
                        max_length=30,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default rule for the platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
                "ordering": ["workspace", "platform", "name"],
            },
        ),
        migrations.CreateModel(
            name="RuleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Text to prepend to the dimension value",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Text to append to the dimension value",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        blank=True,
                        default="-",
                        help_text="Character to separate this dimension from others",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "dimension_order",
                    models.SmallIntegerField(
                        help_text="Order of this dimension in the naming sequence (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this dimension is required for string generation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Detail",
                "verbose_name_plural": "Rule Details",
                "ordering": ["workspace", "rule", "entity", "dimension_order"],
            },
        ),
        migrations.CreateModel(
            name="String",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Generated string value following naming convention",
                        max_length=400,
                    ),
                ),
                (
                    "string_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this string (unique per workspace)",
                    ),
                ),
                (
                    "parent_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of parent string for hierarchical linking",
                        null=True,
                    ),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this string was automatically generated",
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata about how this string was generated",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Current version number for tracking modifications",
                    ),
                ),
            ],
            options={
                "verbose_name": "String",
                "verbose_name_plural": "Strings",
                "ordering": ["workspace", "entity__entity_level", "value"],
            },
        ),
        migrations.CreateModel(
            name="StringDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "dimension_value_freetext",
                    models.CharField(
                        blank=True,
                        help_text="Free-text dimension value (for text-type dimensions)",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "String Detail",
                "verbose_name_plural": "String Details",
                "ordering": ["workspace", "string", "dimension"],
            },
        ),
        migrations.CreateModel(
            name="StringInheritanceUpdate",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inherited_fields",
                    models.JSONField(
                        help_text="Fields that were inherited from parent"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the inheritance update was applied",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Inheritance Update",
                "verbose_name_plural": "String Inheritance Updates",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="StringModification",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        help_text="Version number for this modification"
                    ),
                ),
                (
                    "field_updates",
                    models.JSONField(
                        help_text="JSON object containing field updates made"
                    ),
                ),
                (
                    "string_value",
                    models.TextField(help_text="String value after this modification"),
                ),
                (
                    "original_values",
                    models.JSONField(help_text="Original values before modification"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this modification was made"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("direct_edit", "Direct Edit"),
                            ("inheritance_update", "Inheritance Update"),
                            ("batch_update", "Batch Update"),
                            ("regeneration", "Regeneration"),
                        ],
                        help_text="Type of change that was made",
                        max_length=50,
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of batch operation if part of batch",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the modification",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Modification",
                "verbose_name_plural": "String Modifications",
                "ordering": ["-modified_at"],
            },
        ),
        migrations.CreateModel(
            name="StringUpdateBatch",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the batch operation was started",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the batch operation completed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the batch operation",
                        max_length=20,
                    ),
                ),
                (
                    "total_strings",
                    models.IntegerField(help_text="Total number of strings to update"),
                ),
                (
                    "processed_strings",
                    models.IntegerField(
                        default=0, help_text="Number of strings successfully processed"
                    ),
                ),
                (
                    "failed_strings",
                    models.IntegerField(
                        default=0, help_text="Number of strings that failed to process"
                    ),
                ),
                (
                    "backup_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of backup created before this operation",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the batch operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Update Batch",
                "verbose_name_plural": "String Update Batches",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this submission", max_length=30
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this submission",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Current status of this submission",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["workspace", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this workspace",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default=master_data.models.base.default_workspace_logo,
                        help_text="Logo image for this workspace",
                        null=True,
                        upload_to="workspaces/logos/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this workspace",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "ordering": ["name"],
            },
        ),
    ]
