# Generated by Django 4.2.17 on 2025-08-24 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import master_data.models.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this dimension (unique per workspace)",
                        max_length=30,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this dimension represents",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("list", "List"), ("text", "Free Text")],
                        default="list",
                        help_text="Type of dimension: list of values or free text",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this dimension",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent dimension if this is a sub-dimension",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_dimensions",
                        to="master_data.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension",
                "verbose_name_plural": "Dimensions",
                "ordering": ["workspace", "name"],
            },
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The actual value (e.g., 'prod', 'dev')",
                        max_length=30,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label for this value", max_length=50
                    ),
                ),
                (
                    "utm",
                    models.CharField(
                        help_text="UTM or tracking code for this value", max_length=30
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this value represents",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Date from which this value is valid",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date until which this value is valid",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="The dimension this value belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension_values",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent value if this is a sub-value",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_dimension_values",
                        to="master_data.dimensionvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension Value",
                "verbose_name_plural": "Dimension Values",
                "ordering": ["workspace", "dimension", "value"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this field (e.g., 'environment', 'project')",
                        max_length=30,
                    ),
                ),
                (
                    "field_level",
                    models.SmallIntegerField(
                        help_text="Hierarchical level of this field (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "next_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="Next field in the hierarchy sequence",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_fields",
                        to="master_data.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
                "ordering": ["platform", "field_level"],
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "platform_type",
                    models.CharField(
                        help_text="Type or category of this platform", max_length=30
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the platform", max_length=30
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for this platform"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the icon to display for this platform",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this naming rule", max_length=50
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this rule generates",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this rule",
                        max_length=30,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default rule for the platform",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Platform this rule applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="master_data.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
                "ordering": ["workspace", "platform", "name"],
            },
        ),
        migrations.CreateModel(
            name="String",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Generated string value following naming convention",
                        max_length=400,
                    ),
                ),
                (
                    "string_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this string (unique per workspace)",
                    ),
                ),
                (
                    "parent_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of parent string for hierarchical linking",
                        null=True,
                    ),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this string was automatically generated",
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata about how this string was generated",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Current version number for tracking modifications",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field this string belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_strings",
                        to="master_data.field",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent string in hierarchical naming structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_strings",
                        to="master_data.string",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        editable=False,
                        help_text="Rule used to generate this string (auto-set from submission)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_strings",
                        to="master_data.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "String",
                "verbose_name_plural": "Strings",
                "ordering": ["workspace", "field__field_level", "value"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this workspace",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default=master_data.models.base.default_workspace_logo,
                        help_text="Logo image for this workspace",
                        null=True,
                        upload_to="workspaces/logos/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Current status of this workspace",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this submission", max_length=30
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this submission",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Current status of this submission",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="The naming rule to apply for this submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="master_data.rule",
                    ),
                ),
                (
                    "starting_field",
                    models.ForeignKey(
                        help_text="The field to start the naming sequence from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_field",
                        to="master_data.field",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["workspace", "-created"],
                "unique_together": {("workspace", "name")},
            },
        ),
        migrations.CreateModel(
            name="StringModification",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        help_text="Version number for this modification"
                    ),
                ),
                (
                    "field_updates",
                    models.JSONField(
                        help_text="JSON object containing field updates made"
                    ),
                ),
                (
                    "string_value",
                    models.TextField(help_text="String value after this modification"),
                ),
                (
                    "original_values",
                    models.JSONField(help_text="Original values before modification"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this modification was made"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("direct_edit", "Direct Edit"),
                            ("inheritance_update", "Inheritance Update"),
                            ("batch_update", "Batch Update"),
                            ("regeneration", "Regeneration"),
                        ],
                        help_text="Type of change that was made",
                        max_length=50,
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of batch operation if part of batch",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the modification",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="User who made this modification",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent version that triggered this change",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_versions",
                        to="master_data.stringmodification",
                    ),
                ),
                (
                    "string",
                    models.ForeignKey(
                        help_text="String that was modified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="master_data.string",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Modification",
                "verbose_name_plural": "String Modifications",
                "ordering": ["-modified_at"],
            },
        ),
        migrations.CreateModel(
            name="StringInheritanceUpdate",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inherited_fields",
                    models.JSONField(
                        help_text="Fields that were inherited from parent"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the inheritance update was applied",
                    ),
                ),
                (
                    "child_string",
                    models.ForeignKey(
                        help_text="Child string that received inherited changes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inheritance_received",
                        to="master_data.string",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_modification",
                    models.ForeignKey(
                        help_text="Parent modification that triggered this inheritance update",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inheritance_updates",
                        to="master_data.stringmodification",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Inheritance Update",
                "verbose_name_plural": "String Inheritance Updates",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="StringDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "dimension_value_freetext",
                    models.CharField(
                        blank=True,
                        help_text="Free-text dimension value (for text-type dimensions)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="Dimension this value represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="string_details",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "dimension_value",
                    models.ForeignKey(
                        blank=True,
                        help_text="Predefined dimension value (for list-type dimensions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="string_details",
                        to="master_data.dimensionvalue",
                    ),
                ),
                (
                    "string",
                    models.ForeignKey(
                        help_text="String this detail belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="string_details",
                        to="master_data.string",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Detail",
                "verbose_name_plural": "String Details",
                "ordering": ["workspace", "string", "dimension"],
            },
        ),
        migrations.AddField(
            model_name="string",
            name="submission",
            field=models.ForeignKey(
                help_text="Submission that generated this string",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_strings",
                to="master_data.submission",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.CreateModel(
            name="RuleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Text to prepend to the dimension value",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Text to append to the dimension value",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "delimiter",
                    models.CharField(
                        blank=True,
                        default="-",
                        help_text="Character to separate this dimension from others",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "dimension_order",
                    models.SmallIntegerField(
                        help_text="Order of this dimension in the naming sequence (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this dimension is required for string generation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="Dimension this formatting applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_details",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field this formatting applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_details",
                        to="master_data.field",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="Rule this detail belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_details",
                        to="master_data.rule",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Detail",
                "verbose_name_plural": "Rule Details",
                "ordering": ["workspace", "rule", "field", "dimension_order"],
            },
        ),
        migrations.AddField(
            model_name="rule",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.CreateModel(
            name="PropagationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict, help_text="User-specific propagation settings"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User these settings belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propagation_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propagation Settings",
                "verbose_name_plural": "Propagation Settings",
            },
        ),
        migrations.CreateModel(
            name="PropagationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this propagation batch",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("partial_failure", "Partial Failure"),
                        ],
                        default="pending",
                        help_text="Current status of the propagation job",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job actually started processing",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job completed or failed",
                        null=True,
                    ),
                ),
                (
                    "total_strings",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of strings to be processed"
                    ),
                ),
                (
                    "processed_strings",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of strings successfully processed"
                    ),
                ),
                (
                    "failed_strings",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of strings that failed processing"
                    ),
                ),
                (
                    "max_depth",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum propagation depth configured for this job",
                    ),
                ),
                (
                    "processing_method",
                    models.CharField(
                        choices=[
                            ("synchronous", "Synchronous"),
                            ("background", "Background"),
                            ("chunked", "Chunked Processing"),
                        ],
                        default="synchronous",
                        help_text="Processing method used for this job",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the job configuration and execution",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if job failed", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        help_text="User who triggered this propagation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_propagation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propagation Job",
                "verbose_name_plural": "Propagation Jobs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PropagationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("string_generation_error", "String Generation Error"),
                            ("database_error", "Database Error"),
                            ("validation_error", "Validation Error"),
                            ("circular_dependency", "Circular Dependency"),
                            ("conflict_error", "Conflict Error"),
                            ("permission_error", "Permission Error"),
                            ("timeout_error", "Timeout Error"),
                            ("unknown_error", "Unknown Error"),
                        ],
                        help_text="Type of error that occurred",
                        max_length=30,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(help_text="Human-readable error message"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable error code",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "stack_trace",
                    models.TextField(
                        blank=True, help_text="Full stack trace of the error", null=True
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data about the error",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this operation has been retried",
                    ),
                ),
                (
                    "is_retryable",
                    models.BooleanField(
                        default=False, help_text="Whether this error can be retried"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Whether this error has been resolved"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this error was resolved", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Propagation job this error belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="master_data.propagationjob",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who resolved this error",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_propagation_errors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "string",
                    models.ForeignKey(
                        blank=True,
                        help_text="String that caused the error (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propagation_errors",
                        to="master_data.string",
                    ),
                ),
                (
                    "string_detail",
                    models.ForeignKey(
                        blank=True,
                        help_text="StringDetail that caused the error (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propagation_errors",
                        to="master_data.stringdetail",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propagation Error",
                "verbose_name_plural": "Propagation Errors",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="field",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this field belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="master_data.platform",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="dimension",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.CreateModel(
            name="StringUpdateBatch",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the batch operation was started",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the batch operation completed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the batch operation",
                        max_length=20,
                    ),
                ),
                (
                    "total_strings",
                    models.IntegerField(help_text="Total number of strings to update"),
                ),
                (
                    "processed_strings",
                    models.IntegerField(
                        default=0, help_text="Number of strings successfully processed"
                    ),
                ),
                (
                    "failed_strings",
                    models.IntegerField(
                        default=0, help_text="Number of strings that failed to process"
                    ),
                ),
                (
                    "backup_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of backup created before this operation",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the batch operation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field being updated in this batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.field",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        help_text="User who initiated this batch operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="Rule being updated in this batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.rule",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "String Update Batch",
                "verbose_name_plural": "String Update Batches",
                "ordering": ["-initiated_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="master_data_workspa_a9e9e4_idx",
                    ),
                    models.Index(
                        fields=["initiated_by", "initiated_at"],
                        name="master_data_initiat_8b7c81_idx",
                    ),
                    models.Index(
                        fields=["rule", "field"], name="master_data_rule_id_8871b0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["string", "version"], name="master_data_string__be55fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["batch_id"], name="master_data_batch_i_3b1f74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["modified_at"], name="master_data_modifie_389c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["workspace", "string"], name="master_data_workspa_eea181_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stringmodification",
            constraint=models.UniqueConstraint(
                fields=("string", "version"), name="unique_string_version"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["parent_modification"], name="master_data_parent__216de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["child_string"], name="master_data_child_s_7bc012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["workspace", "applied_at"],
                name="master_data_workspa_f8d7dc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stringinheritanceupdate",
            constraint=models.UniqueConstraint(
                fields=("parent_modification", "child_string"),
                name="unique_inheritance_update",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stringdetail", unique_together={("workspace", "string", "dimension")},
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "rule", "field"],
                name="master_data_workspa_d655d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "string_uuid"],
                name="master_data_workspa_acdcc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "value"], name="master_data_workspa_6947b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="string", unique_together={("workspace", "rule", "field", "value")},
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["workspace", "rule", "field"],
                name="master_data_workspa_f3369d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["workspace", "dimension"], name="master_data_workspa_9de020_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ruledetail",
            unique_together={
                ("workspace", "rule", "field", "dimension", "dimension_order")
            },
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["workspace", "platform", "status"],
                name="master_data_workspa_a5ef98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["workspace", "is_default"],
                name="master_data_workspa_ad5e78_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rule", unique_together={("workspace", "platform", "name")},
        ),
        migrations.AddIndex(
            model_name="propagationsettings",
            index=models.Index(
                fields=["workspace", "user"], name="master_data_workspa_2c1b07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propagationsettings", unique_together={("user", "workspace")},
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["workspace", "status"], name="master_data_workspa_9e06aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["workspace", "triggered_by"],
                name="master_data_workspa_9f76b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["batch_id"], name="master_data_batch_i_1633f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["created"], name="master_data_created_5f07a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["workspace", "error_type"],
                name="master_data_workspa_eca2f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["workspace", "resolved"], name="master_data_workspa_d988fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["job", "error_type"], name="master_data_job_id_ebf23d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["created"], name="master_data_created_1b222d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(name="platform", unique_together={("slug",)},),
        migrations.AlterUniqueTogether(
            name="field", unique_together={("platform", "name", "field_level")},
        ),
        migrations.AlterUniqueTogether(
            name="dimensionvalue",
            unique_together={("workspace", "dimension", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="dimension",
            unique_together={("workspace", "name"), ("workspace", "slug")},
        ),
    ]
