# Generated by Django 4.1 on 2023-08-28 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='master_data.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('platform_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('platform_field', models.CharField(max_length=30)),
                ('field_level', models.SmallIntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='master_data.workspace')),
            ],
            options={
                'unique_together': {('name', 'platform_field', 'field_level')},
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('definition', models.TextField(blank=True, max_length=500, null=True)),
                ('dimension_type', models.CharField(choices=[('mastered', 'Mastered'), ('free-text', 'Free Text'), ('rule', 'Rule'), ('free-text-with-validations', 'Free Text With Validations')], default='mastered', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='master_data.dimension')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='master_data.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delimeter_after_dimension', models.CharField(blank=True, max_length=1, null=True)),
                ('delimeter_before_dimension', models.CharField(blank=True, max_length=1, null=True)),
                ('dimension_order', models.SmallIntegerField()),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.dimension')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.platform')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.rule')),
            ],
            options={
                'unique_together': {('rule', 'platform', 'dimension_order')},
            },
        ),
        migrations.CreateModel(
            name='JunkDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dimension_value_code', models.CharField(max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, max_length=500, null=True)),
                ('dimension_value', models.CharField(max_length=30)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('dimension_value_label', models.CharField(max_length=50)),
                ('dimension_value_utm', models.CharField(max_length=30)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junk_dimension', to='master_data.dimension')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junk_dimension', to='master_data.junkdimension')),
            ],
            options={
                'unique_together': {('dimension', 'dimension_value')},
            },
        ),
    ]
