# Generated by Django 4.2.20 on 2025-05-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="icon_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
