# Generated by Django 4.1 on 2023-09-05 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structure',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.dimension'),
        ),
        migrations.AddField(
            model_name='structure',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.platform'),
        ),
        migrations.AddField(
            model_name='structure',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.rule'),
        ),
        migrations.AddField(
            model_name='rule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='master_data.workspace'),
        ),
        migrations.AddField(
            model_name='platform',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='master_data.workspace'),
        ),
        migrations.AddField(
            model_name='junkdimension',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junk_dimension', to='master_data.dimension'),
        ),
        migrations.AddField(
            model_name='junkdimension',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junk_dimension', to='master_data.junkdimension'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='master_data.dimension'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='master_data.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together={('rule', 'platform', 'dimension_order')},
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('workspace', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('name', 'platform_field', 'field_level')},
        ),
        migrations.AlterUniqueTogether(
            name='junkdimension',
            unique_together={('dimension', 'dimension_value')},
        ),
    ]
