# Generated by Django 4.2.20 on 2025-06-28 22:26

from django.db import migrations, models
import django.db.models.deletion


def add_workspace_fields_if_missing(apps, schema_editor):
    """
    Add workspace fields to models that don't have them.
    This function will only add fields if they don't already exist.
    """
    from django.db import connection

    # Get the database introspection
    introspection = connection.introspection

    # List of models and their table names that need workspace fields
    models_to_update = [
        ('Dimension', 'master_data_dimension'),
        ('DimensionValue', 'master_data_dimensionvalue'),
        ('Platform', 'master_data_platform'),
        ('Field', 'master_data_field'),
        ('Rule', 'master_data_rule'),
        ('RuleDetail', 'master_data_ruledetail'),
        ('String', 'master_data_string'),
        ('StringDetail', 'master_data_stringdetail'),
        ('Submission', 'master_data_submission'),
    ]

    # Check which tables exist and need workspace_id column
    with connection.cursor() as cursor:
        existing_tables = introspection.table_names(cursor)

        for model_name, table_name in models_to_update:
            if table_name in existing_tables:
                # Check if workspace_id column exists
                columns = [col.name for col in introspection.get_table_description(
                    cursor, table_name)]

                if 'workspace_id' not in columns:
                    print(f"Adding workspace_id to {table_name}")

                    # Add the column as nullable first
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        ADD COLUMN workspace_id BIGINT
                    """)

                    # Set default value (assuming workspace with id=1 exists)
                    cursor.execute(f"""
                        UPDATE {table_name} 
                        SET workspace_id = 1 
                        WHERE workspace_id IS NULL
                    """)

                    # Make the column non-nullable
                    if connection.vendor == 'postgresql':
                        cursor.execute(f"""
                            ALTER TABLE {table_name} 
                            ALTER COLUMN workspace_id SET NOT NULL
                        """)

                        # Add foreign key constraint
                        cursor.execute(f"""
                            ALTER TABLE {table_name} 
                            ADD CONSTRAINT {table_name}_workspace_id_fkey 
                            FOREIGN KEY (workspace_id) REFERENCES master_data_workspace(id) ON DELETE CASCADE
                        """)
                    elif connection.vendor == 'sqlite':
                        # SQLite doesn't support ALTER COLUMN, so we'll leave it as is
                        # The NOT NULL constraint will be handled by Django when it recreates tables
                        pass
                else:
                    print(f"workspace_id already exists in {table_name}")


def reverse_add_workspace_fields(apps, schema_editor):
    """
    Remove workspace fields (reverse operation)
    """
    from django.db import connection

    tables_to_update = [
        'master_data_dimension',
        'master_data_dimensionvalue',
        'master_data_platform',
        'master_data_field',
        'master_data_rule',
        'master_data_ruledetail',
        'master_data_string',
        'master_data_stringdetail',
        'master_data_submission',
    ]

    with connection.cursor() as cursor:
        for table_name in tables_to_update:
            try:
                if connection.vendor == 'postgresql':
                    cursor.execute(
                        f"ALTER TABLE {table_name} DROP COLUMN IF EXISTS workspace_id CASCADE")
                elif connection.vendor == 'sqlite':
                    # SQLite doesn't support DROP COLUMN easily, so we'll skip the reverse
                    pass
            except Exception as e:
                print(f"Could not remove workspace_id from {table_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            add_workspace_fields_if_missing,
            reverse_add_workspace_fields,
        ),
    ]
