# Generated by Django 4.2.7 on 2025-11-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="rule",
            field=models.ForeignKey(
                help_text="The naming rule to apply for this submission",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="master_data.rule",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="starting_entity",
            field=models.ForeignKey(
                help_text="The field to start the naming sequence from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_entity",
                to="master_data.entity",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stringupdatebatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stringupdatebatch",
            name="entity",
            field=models.ForeignKey(
                help_text="Field being updated in this batch",
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.entity",
            ),
        ),
        migrations.AddField(
            model_name="stringupdatebatch",
            name="initiated_by",
            field=models.ForeignKey(
                help_text="User who initiated this batch operation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stringupdatebatch",
            name="rule",
            field=models.ForeignKey(
                help_text="Rule being updated in this batch",
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.rule",
            ),
        ),
        migrations.AddField(
            model_name="stringupdatebatch",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stringmodification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stringmodification",
            name="modified_by",
            field=models.ForeignKey(
                help_text="User who made this modification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stringmodification",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent version that triggered this change",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_versions",
                to="master_data.stringmodification",
            ),
        ),
        migrations.AddField(
            model_name="stringmodification",
            name="string",
            field=models.ForeignKey(
                help_text="String that was modified",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifications",
                to="master_data.string",
            ),
        ),
        migrations.AddField(
            model_name="stringmodification",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stringinheritanceupdate",
            name="child_string",
            field=models.ForeignKey(
                help_text="Child string that received inherited changes",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inheritance_received",
                to="master_data.string",
            ),
        ),
        migrations.AddField(
            model_name="stringinheritanceupdate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stringinheritanceupdate",
            name="parent_modification",
            field=models.ForeignKey(
                help_text="Parent modification that triggered this inheritance update",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inheritance_updates",
                to="master_data.stringmodification",
            ),
        ),
        migrations.AddField(
            model_name="stringinheritanceupdate",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="stringdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stringdetail",
            name="dimension",
            field=models.ForeignKey(
                help_text="Dimension this value represents",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="string_details",
                to="master_data.dimension",
            ),
        ),
        migrations.AddField(
            model_name="stringdetail",
            name="dimension_value",
            field=models.ForeignKey(
                blank=True,
                help_text="Predefined dimension value (for list-type dimensions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="string_details",
                to="master_data.dimensionvalue",
            ),
        ),
        migrations.AddField(
            model_name="stringdetail",
            name="string",
            field=models.ForeignKey(
                help_text="String this detail belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="string_details",
                to="master_data.string",
            ),
        ),
        migrations.AddField(
            model_name="stringdetail",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this string",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_strings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="entity",
            field=models.ForeignKey(
                help_text="Entity this string belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_strings",
                to="master_data.entity",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent string in hierarchical naming structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_strings",
                to="master_data.string",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="rule",
            field=models.ForeignKey(
                editable=False,
                help_text="Rule used to generate this string (auto-set from submission)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_strings",
                to="master_data.rule",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                help_text="[DEPRECATED] Submission that generated this string. Use projects instead.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_strings",
                to="master_data.submission",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="ruledetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ruledetail",
            name="dimension",
            field=models.ForeignKey(
                help_text="Dimension this formatting applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_details",
                to="master_data.dimension",
            ),
        ),
        migrations.AddField(
            model_name="ruledetail",
            name="entity",
            field=models.ForeignKey(
                help_text="Entity this formatting applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_details",
                to="master_data.entity",
            ),
        ),
        migrations.AddField(
            model_name="ruledetail",
            name="rule",
            field=models.ForeignKey(
                help_text="Rule this detail belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_details",
                to="master_data.rule",
            ),
        ),
        migrations.AddField(
            model_name="ruledetail",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this rule applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="master_data.platform",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="propagationsettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationsettings",
            name="user",
            field=models.ForeignKey(
                help_text="User these settings belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="propagation_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationsettings",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="propagationjob",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationjob",
            name="triggered_by",
            field=models.ForeignKey(
                help_text="User who triggered this propagation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_propagation_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationjob",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="propagationerror",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationerror",
            name="job",
            field=models.ForeignKey(
                help_text="Propagation job this error belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errors",
                to="master_data.propagationjob",
            ),
        ),
        migrations.AddField(
            model_name="propagationerror",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who resolved this error",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_propagation_errors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationerror",
            name="string",
            field=models.ForeignKey(
                blank=True,
                help_text="String that caused the error (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propagation_errors",
                to="master_data.string",
            ),
        ),
        migrations.AddField(
            model_name="propagationerror",
            name="string_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="StringDetail that caused the error (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propagation_errors",
                to="master_data.stringdetail",
            ),
        ),
        migrations.AddField(
            model_name="propagationerror",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="projectstringdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectstringdetail",
            name="dimension",
            field=models.ForeignKey(
                help_text="Dimension this value represents",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_string_details",
                to="master_data.dimension",
            ),
        ),
        migrations.AddField(
            model_name="projectstringdetail",
            name="dimension_value",
            field=models.ForeignKey(
                blank=True,
                help_text="Predefined dimension value (for list-type dimensions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_string_details",
                to="master_data.dimensionvalue",
            ),
        ),
        migrations.AddField(
            model_name="projectstringdetail",
            name="string",
            field=models.ForeignKey(
                help_text="Project string this detail belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="master_data.projectstring",
            ),
        ),
        migrations.AddField(
            model_name="projectstringdetail",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this string",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_project_strings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="entity",
            field=models.ForeignKey(
                help_text="Entity this string belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_entity_strings",
                to="master_data.entity",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent string in hierarchical naming structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="master_data.projectstring",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this string belongs to (via project platform assignment)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_strings",
                to="master_data.platform",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="project",
            field=models.ForeignKey(
                help_text="Project this string belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strings",
                to="master_data.project",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="rule",
            field=models.ForeignKey(
                help_text="Rule used to generate this string",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_rule_strings",
                to="master_data.rule",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="project",
            field=models.ForeignKey(
                help_text="Project this member belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_members",
                to="master_data.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                help_text="User assigned to this project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="project",
            field=models.ForeignKey(
                help_text="Project this activity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="master_data.project",
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                help_text="Project owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="platforms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Platforms assigned to this project",
                related_name="projects",
                to="master_data.platform",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who rejected this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="next_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Next entity in the hierarchy sequence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_entities",
                to="master_data.entity",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this entity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="master_data.platform",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="dimension",
            field=models.ForeignKey(
                help_text="The dimension this value belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimension_values",
                to="master_data.dimension",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent value if this is a sub-value",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_dimension_values",
                to="master_data.dimensionvalue",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="dimensionconstraint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dimensionconstraint",
            name="dimension",
            field=models.ForeignKey(
                help_text="The dimension this constraint applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraints",
                to="master_data.dimension",
            ),
        ),
        migrations.AddField(
            model_name="dimension",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dimension",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent dimension if this is a sub-dimension",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_dimensions",
                to="master_data.dimension",
            ),
        ),
        migrations.AddField(
            model_name="dimension",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="approvalhistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalhistory",
            name="project",
            field=models.ForeignKey(
                help_text="Project this approval relates to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_history",
                to="master_data.project",
            ),
        ),
        migrations.AddField(
            model_name="approvalhistory",
            name="user",
            field=models.ForeignKey(
                help_text="User who performed this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="stringupdatebatch",
            index=models.Index(
                fields=["workspace", "status"], name="master_data_workspa_a9e9e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringupdatebatch",
            index=models.Index(
                fields=["initiated_by", "initiated_at"],
                name="master_data_initiat_8b7c81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stringupdatebatch",
            index=models.Index(
                fields=["rule", "entity"], name="master_data_rule_id_dadfe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["string", "version"], name="master_data_string__be55fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["batch_id"], name="master_data_batch_i_3b1f74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["modified_at"], name="master_data_modifie_389c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["workspace", "string"], name="master_data_workspa_eea181_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stringmodification",
            constraint=models.UniqueConstraint(
                fields=("string", "version"), name="unique_string_version"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["parent_modification"], name="master_data_parent__216de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["child_string"], name="master_data_child_s_7bc012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["workspace", "applied_at"],
                name="master_data_workspa_f8d7dc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stringinheritanceupdate",
            constraint=models.UniqueConstraint(
                fields=("parent_modification", "child_string"),
                name="unique_inheritance_update",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stringdetail",
            unique_together={("workspace", "string", "dimension")},
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "rule", "entity"],
                name="master_data_workspa_21c051_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "string_uuid"],
                name="master_data_workspa_acdcc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "value"], name="master_data_workspa_6947b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="string",
            unique_together={("workspace", "rule", "entity", "parent", "value")},
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["workspace", "rule", "entity"],
                name="master_data_workspa_b6f003_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["workspace", "dimension"], name="master_data_workspa_9de020_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ruledetail",
            unique_together={
                ("workspace", "rule", "entity", "dimension", "dimension_order")
            },
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["workspace", "platform", "status"],
                name="master_data_workspa_a5ef98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["workspace", "is_default"],
                name="master_data_workspa_ad5e78_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={("workspace", "platform", "name")},
        ),
        migrations.AddIndex(
            model_name="propagationsettings",
            index=models.Index(
                fields=["workspace", "user"], name="master_data_workspa_2c1b07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="propagationsettings",
            unique_together={("user", "workspace")},
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["workspace", "status"], name="master_data_workspa_9e06aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["workspace", "triggered_by"],
                name="master_data_workspa_9f76b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["batch_id"], name="master_data_batch_i_1633f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationjob",
            index=models.Index(
                fields=["created"], name="master_data_created_5f07a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["workspace", "error_type"],
                name="master_data_workspa_eca2f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["workspace", "resolved"], name="master_data_workspa_d988fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["job", "error_type"], name="master_data_job_id_ebf23d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propagationerror",
            index=models.Index(
                fields=["created"], name="master_data_created_1b222d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectstringdetail",
            index=models.Index(
                fields=["string", "dimension"], name="master_data_string__32e211_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectstringdetail",
            unique_together={("workspace", "string", "dimension")},
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["workspace", "project", "platform"],
                name="master_data_workspa_967fd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["workspace", "string_uuid"],
                name="master_data_workspa_a04ca4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["workspace", "parent_uuid"],
                name="master_data_workspa_9f6d22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["project", "platform", "entity"],
                name="master_data_project_b54215_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstring",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=(
                    "workspace",
                    "project",
                    "platform",
                    "entity",
                    "parent",
                    "value",
                ),
                name="unique_with_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstring",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("workspace", "project", "platform", "entity", "value"),
                name="unique_without_parent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="projectactivity",
            index=models.Index(
                fields=["project", "-created"], name="master_data_project_d2f945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "slug"], name="master_data_workspa_2cd34b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "status"], name="master_data_workspa_d8c7ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "owner"], name="master_data_workspa_c06756_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "approval_status"],
                name="master_data_workspa_550d5a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("workspace", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="platform",
            unique_together={("slug",)},
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together={("platform", "name", "entity_level")},
        ),
        migrations.AlterUniqueTogether(
            name="dimensionvalue",
            unique_together={("workspace", "dimension", "value")},
        ),
        migrations.AddIndex(
            model_name="dimensionconstraint",
            index=models.Index(
                fields=["dimension"], name="master_data_dimensi_f7a327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dimensionconstraint",
            index=models.Index(
                fields=["dimension", "is_active"], name="master_data_dimensi_96ff7d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dimensionconstraint",
            unique_together={("dimension", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="dimension",
            unique_together={("workspace", "name"), ("workspace", "slug")},
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(
                fields=["project", "-timestamp"], name="master_data_project_db4330_idx"
            ),
        ),
    ]
