# Generated by Django 4.2.17 on 2025-08-26 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stringmodification",
            name="modified_by",
            field=models.ForeignKey(
                help_text="User who made this modification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="initiated_by",
            field=models.ForeignKey(
                help_text="User who initiated this batch operation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
