# Generated by Django 4.2.20 on 2025-05-31 01:08

from django.db import migrations, models, connection
from django.utils.text import slugify
from django.db.models import Q


def check_column_exists(table_name, column_name):
    """
    Check if a column exists in a table
    """
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns 
            WHERE table_name = %s AND column_name = %s
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0


def add_slug_column_if_not_exists(apps, schema_editor):
    """
    Add slug column to Platform model if it doesn't exist
    """
    # Check if slug column already exists
    if check_column_exists('master_data_platform', 'slug'):
        print("Slug column already exists, skipping column creation")
        return

    # Add slug column as nullable first
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE master_data_platform 
            ADD COLUMN slug VARCHAR(50) NULL
        """)

    print("Added slug column to Platform model")


def populate_slugs_if_needed(apps, schema_editor):
    """
    Populate slugs for existing platforms that don't have them
    """
    Platform = apps.get_model('master_data', 'Platform')

    # Get platforms without slugs or with empty slugs
    platforms_without_slugs = Platform.objects.filter(
        Q(slug__isnull=True) | Q(slug='')
    )

    if not platforms_without_slugs.exists():
        print("All platforms already have slugs, skipping population")
        return

    print(f"Populating slugs for {platforms_without_slugs.count()} platforms")

    for platform in platforms_without_slugs:
        base_slug = slugify(platform.name)
        slug = base_slug
        counter = 1

        # Ensure slug uniqueness
        while Platform.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        platform.slug = slug
        platform.save()

    print("Finished populating slugs")


def make_slug_non_nullable_and_unique(apps, schema_editor):
    """
    Make slug field non-nullable and add unique constraint if not already present
    """
    with connection.cursor() as cursor:
        # Check if unique constraint already exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu 
            ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_name = 'master_data_platform' 
            AND tc.constraint_type = 'UNIQUE'
            AND kcu.column_name = 'slug'
        """)

        has_unique_constraint = cursor.fetchone()[0] > 0

        if not has_unique_constraint:
            # Make column NOT NULL
            cursor.execute("""
                ALTER TABLE master_data_platform 
                ALTER COLUMN slug SET NOT NULL
            """)

            # Add unique constraint
            cursor.execute("""
                ALTER TABLE master_data_platform 
                ADD CONSTRAINT master_data_platform_slug_unique 
                UNIQUE (slug)
            """)

            print("Made slug column NOT NULL and added unique constraint")
        else:
            print("Slug column already has proper constraints")


def reverse_add_slug_column(apps, schema_editor):
    """
    Reverse the slug column addition
    """
    # Only drop if column exists
    if check_column_exists('master_data_platform', 'slug'):
        with connection.cursor() as cursor:
            # Drop unique constraint first if it exists
            cursor.execute("""
                ALTER TABLE master_data_platform 
                DROP CONSTRAINT IF EXISTS master_data_platform_slug_unique
            """)

            # Drop the column
            cursor.execute("""
                ALTER TABLE master_data_platform 
                DROP COLUMN slug
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        # Step 1: Add slug column if it doesn't exist
        migrations.RunPython(
            code=add_slug_column_if_not_exists,
            reverse_code=reverse_add_slug_column,
        ),

        # Step 2: Populate slugs for existing records
        migrations.RunPython(
            code=populate_slugs_if_needed,
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 3: Make slug non-nullable and unique
        migrations.RunPython(
            code=make_slug_non_nullable_and_unique,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
