# Generated by Django 4.2.7 on 2025-11-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="string",
            name="external_parent_id",
            field=models.CharField(
                blank=True,
                help_text="Parent's platform identifier for external hierarchy tracking",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="external_platform_id",
            field=models.CharField(
                blank=True,
                help_text="Platform-specific identifier (e.g., Meta campaign_123)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="validation_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validation errors, warnings, and hierarchy conflicts",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="validation_source",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                default="internal",
                help_text="Whether string was generated internally or imported from external platform",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("warning", "Warning"),
                    ("entity_mismatch", "Entity Mismatch"),
                ],
                help_text="Validation status for external strings",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "external_platform_id"],
                name="master_data_workspa_9448e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["validation_source", "validation_status"],
                name="master_data_validat_c825ae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="string",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_platform_id__isnull", False)),
                fields=("workspace", "external_platform_id"),
                name="unique_external_platform_id_per_workspace",
            ),
        ),
    ]
