# Generated by Django 4.2.7 on 2025-10-19 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0002_fix_user_deletion_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimensionConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "constraint_type",
                    models.CharField(
                        choices=[
                            ("no_spaces", "No Spaces"),
                            ("lowercase", "Lowercase Only"),
                            ("uppercase", "Uppercase Only"),
                            ("no_special_chars", "No Special Characters"),
                            ("alphanumeric", "Alphanumeric Only"),
                            ("numeric", "Numeric Only"),
                            ("max_length", "Maximum Length"),
                            ("min_length", "Minimum Length"),
                            ("regex", "Regular Expression"),
                            ("starts_with", "Starts With"),
                            ("ends_with", "Ends With"),
                            ("allowed_chars", "Allowed Characters"),
                            ("no_uppercase", "No Uppercase"),
                            ("no_numbers", "No Numbers"),
                            ("url_safe", "URL Safe"),
                        ],
                        help_text="Type of constraint to apply",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Configuration value for constraints that need it (e.g., max_length, regex pattern)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Custom error message to display when constraint is violated",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which constraint is applied (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this constraint is currently active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="The dimension this constraint applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dimension Constraint",
                "verbose_name_plural": "Dimension Constraints",
                "ordering": ["dimension", "order"],
                "indexes": [
                    models.Index(
                        fields=["dimension"], name="master_data_dimensi_f7a327_idx"
                    ),
                    models.Index(
                        fields=["dimension", "is_active"],
                        name="master_data_dimensi_96ff7d_idx",
                    ),
                ],
                "unique_together": {("dimension", "order")},
            },
        ),
    ]
