# Generated by Django 4.2.20 on 2025-05-30 11:02

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs_safe(apps, schema_editor):
    """
    Safely populate slugs, handling cases where field might not exist yet
    """
    try:
        Platform = apps.get_model('master_data', 'Platform')
        for platform in Platform.objects.all():
            if not getattr(platform, 'slug', None):
                platform.slug = slugify(platform.name)
                platform.save()
    except Exception:
        # Field doesn't exist yet or other error, skip
        pass


def reverse_populate_slugs(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("master_data", "0002_platform_icon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=50, null=True, blank=True),
        ),
        migrations.RunPython(populate_slugs_safe, reverse_populate_slugs),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=50, unique=True),
        ),
    ]
