# Generated by Django 4.1 on 2023-09-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('name', 'workspace')},
        ),
    ]
