# Generated by Django 4.2.20 on 2025-05-30 11:02

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Platform = apps.get_model('master_data', 'Platform')
    for platform in Platform.objects.all():
        platform.slug = slugify(platform.name)
        platform.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    # No need to reverse since we're removing the field
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_platform_icon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=50, null=True, blank=True),
        ),
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=50, unique=True),
        ),
    ]
