# Generated by Django 4.2.7 on 2025-10-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0003_add_dimension_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimensionconstraint",
            name="workspace",
        ),
    ]
