# Generated by Django 4.2.7 on 2025-11-10 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0003_add_external_validation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original CSV file name", max_length=255
                    ),
                ),
                (
                    "file_size_bytes",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(default=0, help_text="Total rows in CSV"),
                ),
                (
                    "uploaded_rows",
                    models.IntegerField(
                        default=0, help_text="Rows uploaded (excluding header)"
                    ),
                ),
                (
                    "processed_rows",
                    models.IntegerField(
                        default=0, help_text="Rows that matched rule entity"
                    ),
                ),
                (
                    "skipped_rows",
                    models.IntegerField(
                        default=0, help_text="Rows with entity mismatch"
                    ),
                ),
                (
                    "created_count",
                    models.IntegerField(default=0, help_text="New Strings created"),
                ),
                (
                    "updated_count",
                    models.IntegerField(
                        default=0, help_text="Existing Strings updated"
                    ),
                ),
                (
                    "valid_count",
                    models.IntegerField(
                        default=0, help_text="Total successful (created + updated)"
                    ),
                ),
                (
                    "warnings_count",
                    models.IntegerField(default=0, help_text="Succeeded with warnings"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, help_text="Failed validation"),
                ),
                (
                    "linked_parents_count",
                    models.IntegerField(
                        default=0, help_text="Successfully linked to parent"
                    ),
                ),
                (
                    "parent_conflicts_count",
                    models.IntegerField(
                        default=0, help_text="Hierarchy conflicts detected"
                    ),
                ),
                (
                    "parent_not_found_count",
                    models.IntegerField(
                        default=0, help_text="Parent external_id not found"
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        blank=True, help_text="Time taken to process upload", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        help_text="Upload processing status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if upload failed",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Platform selected for validation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="master_data.platform",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="Rule used for validation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="master_data.rule",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Batch",
                "verbose_name_plural": "Import Batches",
                "db_table": "master_data_import_batch",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "uploaded_by"],
                        name="master_data_workspa_02e90d_idx",
                    ),
                    models.Index(
                        fields=["workspace", "platform"],
                        name="master_data_workspa_2a3eaa_idx",
                    ),
                    models.Index(
                        fields=["workspace", "created"],
                        name="master_data_workspa_becb0e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="master_data_status_6cc04b_idx"
                    ),
                ],
            },
        ),
    ]
