# Generated by Django 4.1 on 2023-10-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_dimension_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='workspace',
        ),
    ]
