# Generated by Django 4.1 on 2023-10-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_remove_platform_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('field_level', models.SmallIntegerField()),
                ('next_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='master_data.field')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='master_data.platform')),
            ],
            options={
                'unique_together': {('platform', 'name', 'field_level')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='structure',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.field'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together={('rule', 'field', 'dimension_order')},
        ),
        migrations.RemoveField(
            model_name='structure',
            name='platform',
        ),
    ]
