# Generated by Django 4.2.20 on 2025-06-01 15:53

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug_field(apps, schema_editor):
    """Populate slug field for existing Platform records"""
    Platform = apps.get_model('master_data', 'Platform')

    for platform in Platform.objects.all():
        if not platform.slug:  # Only populate if slug is empty
            base_slug = slugify(platform.name)
            slug = base_slug
            counter = 1

            # Ensure uniqueness
            while Platform.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            platform.slug = slug
            platform.save()


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_add_created_by_to_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(max_length=50, null=True, blank=True,
                                   help_text="URL-friendly identifier for this platform"),
        ),
        migrations.RunPython(populate_slug_field, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(
                max_length=50, unique=True, help_text="URL-friendly identifier for this platform"),
        ),
    ]
