# Generated by Django 4.2.20 on 2025-06-01 15:53

from django.db import migrations, models, connection
from django.utils.text import slugify


def check_column_exists(table_name, column_name):
    """Check if a column exists in a table (SQLite compatible)"""
    with connection.cursor() as cursor:
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns


def add_slug_field_if_missing(apps, schema_editor):
    """Add slug field to Platform model if it doesn't exist"""
    if check_column_exists('master_data_platform', 'slug'):
        print("Slug column already exists, skipping creation")
        return

    Platform = apps.get_model('master_data', 'Platform')

    # Add slug column as nullable first
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE master_data_platform 
            ADD COLUMN slug VARCHAR(50)
        """)

    # Populate slugs for existing records
    for platform in Platform.objects.all():
        base_slug = slugify(platform.name)
        slug = base_slug
        counter = 1

        # Ensure uniqueness
        while Platform.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        platform.slug = slug
        platform.save()

    # For SQLite, we need to recreate the table to add NOT NULL and UNIQUE constraints
    # This is a simplified approach - in production, you might want a more robust solution
    print("Successfully added slug field to Platform model")


def remove_slug_field(apps, schema_editor):
    """Remove slug field from Platform model"""
    if not check_column_exists('master_data_platform', 'slug'):
        return

    # Note: SQLite doesn't support dropping columns easily
    # This is a simplified reverse operation
    print("Note: SQLite doesn't support dropping columns easily. Manual intervention may be required.")


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_add_created_by_to_all_models'),
    ]

    operations = [
        migrations.RunPython(
            code=add_slug_field_if_missing,
            reverse_code=remove_slug_field,
        ),
    ]
