# Generated by Django 4.2.7 on 2025-11-11 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0004_importbatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The external string value", max_length=400
                    ),
                ),
                (
                    "external_platform_id",
                    models.CharField(
                        db_index=True,
                        help_text="Platform-specific identifier (e.g., campaign_123)",
                        max_length=100,
                    ),
                ),
                (
                    "external_parent_id",
                    models.CharField(
                        blank=True,
                        help_text="Parent's platform identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("warning", "Warning"),
                            ("skipped", "Skipped - Entity Mismatch"),
                        ],
                        help_text="Validation result",
                        max_length=20,
                    ),
                ),
                (
                    "validation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed values, errors, warnings, hierarchy conflicts",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this was imported to a project",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number (increments on re-upload)"
                    ),
                ),
            ],
            options={
                "verbose_name": "External String",
                "verbose_name_plural": "External Strings",
                "db_table": "master_data_external_string",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ExternalStringBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original CSV file name", max_length=255
                    ),
                ),
                (
                    "file_size_bytes",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("validation", "Validation Only"),
                            ("import", "Import to Project"),
                        ],
                        default="validation",
                        help_text="Type of operation performed",
                        max_length=20,
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(default=0, help_text="Total rows in CSV"),
                ),
                (
                    "uploaded_rows",
                    models.IntegerField(
                        default=0, help_text="Rows uploaded (excluding header)"
                    ),
                ),
                (
                    "processed_rows",
                    models.IntegerField(
                        default=0, help_text="Rows successfully processed"
                    ),
                ),
                (
                    "skipped_rows",
                    models.IntegerField(
                        default=0,
                        help_text="Rows skipped (entity mismatch, duplicates)",
                    ),
                ),
                (
                    "created_count",
                    models.IntegerField(
                        default=0, help_text="ExternalStrings or ProjectStrings created"
                    ),
                ),
                (
                    "updated_count",
                    models.IntegerField(
                        default=0,
                        help_text="ProjectStrings updated (import operation only)",
                    ),
                ),
                (
                    "valid_count",
                    models.IntegerField(
                        default=0, help_text="Strings that passed validation"
                    ),
                ),
                (
                    "warnings_count",
                    models.IntegerField(
                        default=0, help_text="Strings with warnings (but still valid)"
                    ),
                ),
                (
                    "failed_count",
                    models.IntegerField(
                        default=0, help_text="Strings that failed validation"
                    ),
                ),
                (
                    "linked_parents_count",
                    models.IntegerField(
                        default=0, help_text="Successfully linked to parent"
                    ),
                ),
                (
                    "parent_conflicts_count",
                    models.IntegerField(
                        default=0, help_text="Hierarchy conflicts detected"
                    ),
                ),
                (
                    "parent_not_found_count",
                    models.IntegerField(
                        default=0, help_text="Parent external_id not found"
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to process the upload",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        help_text="Processing status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "External String Batch",
                "verbose_name_plural": "External String Batches",
                "db_table": "master_data_external_string_batch",
                "ordering": ["-created"],
            },
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="rule",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="importbatch",
            name="workspace",
        ),
        migrations.AddField(
            model_name="projectstring",
            name="external_parent_id",
            field=models.CharField(
                blank=True,
                help_text="Parent's platform identifier (for external hierarchy tracking)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="external_platform_id",
            field=models.CharField(
                blank=True,
                help_text="Platform-specific identifier (for imported external strings, e.g., campaign_123)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="Last sync with external platform", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="sync_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_sync", "In Sync"),
                    ("out_of_sync", "Out of Sync"),
                    ("conflict", "Conflict"),
                ],
                help_text="Sync status with external platform",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="validation_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validation data at time of import (parsed values, errors, warnings)",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="validation_source",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                default="internal",
                help_text="Whether string was generated internally or imported from external platform",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["workspace", "external_platform_id"],
                name="master_data_workspa_a92fea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["validation_source", "sync_status"],
                name="master_data_validat_dd0785_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstring",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("external_platform_id__isnull", False),
                    ("validation_source", "external"),
                ),
                fields=("workspace", "external_platform_id"),
                name="unique_project_string_external_id",
            ),
        ),
        migrations.DeleteModel(
            name="ImportBatch",
        ),
        migrations.AddField(
            model_name="externalstringbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalstringbatch",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform the strings came from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_string_batches",
                to="master_data.platform",
            ),
        ),
        migrations.AddField(
            model_name="externalstringbatch",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project (only for 'import' operation type)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_string_batches",
                to="master_data.project",
            ),
        ),
        migrations.AddField(
            model_name="externalstringbatch",
            name="rule",
            field=models.ForeignKey(
                help_text="Rule used for validation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_string_batches",
                to="master_data.rule",
            ),
        ),
        migrations.AddField(
            model_name="externalstringbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_string_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalstringbatch",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="batch",
            field=models.ForeignKey(
                help_text="Batch this string belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_strings",
                to="master_data.externalstringbatch",
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who uploaded this",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_external_strings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="entity",
            field=models.ForeignKey(
                help_text="Entity type of this string",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_strings",
                to="master_data.entity",
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="imported_to_project_string",
            field=models.ForeignKey(
                blank=True,
                help_text="If imported to project, link to ProjectString",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_external_strings",
                to="master_data.projectstring",
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this string came from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_strings",
                to="master_data.platform",
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="rule",
            field=models.ForeignKey(
                help_text="Rule used for validation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_strings",
                to="master_data.rule",
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="If re-uploaded, link to newer version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="master_data.externalstring",
            ),
        ),
        migrations.AddField(
            model_name="externalstring",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddField(
            model_name="projectstring",
            name="source_external_string",
            field=models.ForeignKey(
                blank=True,
                help_text="Source ExternalString if imported from validation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imported_project_strings",
                to="master_data.externalstring",
            ),
        ),
        migrations.AddIndex(
            model_name="externalstringbatch",
            index=models.Index(
                fields=["workspace", "uploaded_by"],
                name="master_data_workspa_fec794_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalstringbatch",
            index=models.Index(
                fields=["workspace", "platform"], name="master_data_workspa_8afb15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalstringbatch",
            index=models.Index(
                fields=["workspace", "project"], name="master_data_workspa_40fac9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalstringbatch",
            index=models.Index(
                fields=["workspace", "created"], name="master_data_workspa_8150a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalstringbatch",
            index=models.Index(
                fields=["operation_type"], name="master_data_operati_0c08d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalstringbatch",
            index=models.Index(fields=["status"], name="master_data_status_c13376_idx"),
        ),
        migrations.AddIndex(
            model_name="externalstring",
            index=models.Index(
                fields=["workspace", "external_platform_id"],
                name="master_data_workspa_2724bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalstring",
            index=models.Index(
                fields=["workspace", "validation_status"],
                name="master_data_workspa_57235f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalstring",
            index=models.Index(
                fields=["workspace", "platform", "entity"],
                name="master_data_workspa_8ff39c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalstring",
            index=models.Index(fields=["batch"], name="master_data_batch_i_ee356d_idx"),
        ),
        migrations.AddIndex(
            model_name="externalstring",
            index=models.Index(
                fields=["imported_to_project_string"],
                name="master_data_importe_ebcfb2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalstring",
            constraint=models.UniqueConstraint(
                condition=models.Q(("superseded_by__isnull", True)),
                fields=("workspace", "external_platform_id", "batch"),
                name="unique_external_id_per_batch",
            ),
        ),
    ]
