# Generated by Django 4.2.7 on 2025-10-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0004_remove_workspace_from_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="string",
            unique_together={("workspace", "rule", "field", "parent", "value")},
        ),
    ]
