# Generated by Django 4.2.7 on 2025-11-11 01:18

from django.db import migrations


def rename_tables_if_needed(apps, schema_editor):
    """Rename tables only if they still have old names, or drop old tables if both exist."""
    with schema_editor.connection.cursor() as cursor:
        # Check for String tables
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'master_data_projectstring'
            );
        """)
        old_string_exists = cursor.fetchone()[0]

        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'master_data_string'
            );
        """)
        new_string_exists = cursor.fetchone()[0]

        if old_string_exists and new_string_exists:
            # Both exist - drop the old one (assuming new one is correct)
            cursor.execute('DROP TABLE IF EXISTS master_data_projectstring CASCADE;')
        elif old_string_exists and not new_string_exists:
            # Only old exists - rename it
            cursor.execute('ALTER TABLE master_data_projectstring RENAME TO master_data_string;')

        # Check for StringDetail tables
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'master_data_projectstringdetail'
            );
        """)
        old_detail_exists = cursor.fetchone()[0]

        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'master_data_stringdetail'
            );
        """)
        new_detail_exists = cursor.fetchone()[0]

        if old_detail_exists and new_detail_exists:
            # Both exist - drop the old one
            cursor.execute('DROP TABLE IF EXISTS master_data_projectstringdetail CASCADE;')
        elif old_detail_exists and not new_detail_exists:
            # Only old exists - rename it
            cursor.execute('ALTER TABLE master_data_projectstringdetail RENAME TO master_data_stringdetail;')


def reverse_rename_tables(apps, schema_editor):
    """Reverse the table renames."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE master_data_string RENAME TO master_data_projectstring;')
        cursor.execute('ALTER TABLE master_data_stringdetail RENAME TO master_data_projectstringdetail;')


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0005_create_external_string_and_rename_batch"),
    ]

    operations = [
        migrations.RunPython(rename_tables_if_needed, reverse_rename_tables),
    ]
