# Generated by Django 4.1 on 2023-10-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_field_alter_structure_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('name', 'platform_type')},
        ),
        migrations.RemoveField(
            model_name='platform',
            name='field_level',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform_field',
        ),
    ]
