# Generated by Django 4.2.7 on 2025-10-31 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0005_alter_string_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=30)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name (auto-generated)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this project",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        help_text="Current status of this project",
                        max_length=30,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Approval status of this project",
                        max_length=30,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this project was approved",
                        null=True,
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this project was rejected",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Project owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who rejected this project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["workspace", "-created"],
            },
        ),
        migrations.CreateModel(
            name="ProjectString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Generated string value following naming convention",
                        max_length=400,
                    ),
                ),
                (
                    "string_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for this string (globally unique)",
                        unique=True,
                    ),
                ),
                (
                    "parent_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of parent string for hierarchical linking",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this string",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_strings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="Field this string belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_field_strings",
                        to="master_data.field",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent string in hierarchical naming structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="master_data.projectstring",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Platform this string belongs to (via project platform assignment)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_strings",
                        to="master_data.platform",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this string belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strings",
                        to="master_data.project",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="Rule used to generate this string",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_rule_strings",
                        to="master_data.rule",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project String",
                "verbose_name_plural": "Project Strings",
                "ordering": ["workspace", "project", "field__field_level", "value"],
            },
        ),
        migrations.AlterField(
            model_name="string",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this string",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_strings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        help_text="User's role in this project",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this member belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="master_data.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User assigned to this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "ordering": ["project", "user"],
            },
        ),
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("project_created", "Project Created"),
                            ("platform_added", "Platform Added"),
                            ("platform_removed", "Platform Removed"),
                            ("member_assigned", "Member Assigned"),
                            ("member_unassigned", "Member Unassigned"),
                            ("strings_generated", "Strings Generated"),
                            ("status_changed", "Status Changed"),
                            ("project_updated", "Project Updated"),
                            ("submitted_for_approval", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        help_text="Type of activity",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the activity"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="master_data.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Activity",
                "verbose_name_plural": "Project Activities",
                "ordering": ["project", "-created"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        help_text="Approval status of this platform assignment",
                        max_length=30,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this platform assignment was approved",
                        null=True,
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this platform assignment was rejected",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection", null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this platform assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_platform_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users assigned to work on this platform",
                        related_name="platform_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Platform assigned to this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="master_data.platform",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this platform is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_assignments",
                        to="master_data.project",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who rejected this platform assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_platform_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Assignment",
                "verbose_name_plural": "Platform Assignments",
                "ordering": ["project", "platform"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        help_text="Type of approval action",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment or reason", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this action was performed"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform_assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Platform assignment this approval relates to (for platform-level approval)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="master_data.platformassignment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this approval relates to (for project-level approval)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="master_data.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval History",
                "verbose_name_plural": "Approval Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStringDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "dimension_value_freetext",
                    models.CharField(
                        blank=True,
                        help_text="Free-text dimension value (for text-type dimensions)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_inherited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this value was inherited from parent string",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        help_text="Dimension this value represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_string_details",
                        to="master_data.dimension",
                    ),
                ),
                (
                    "dimension_value",
                    models.ForeignKey(
                        blank=True,
                        help_text="Predefined dimension value (for list-type dimensions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_string_details",
                        to="master_data.dimensionvalue",
                    ),
                ),
                (
                    "string",
                    models.ForeignKey(
                        help_text="Project string this detail belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="master_data.projectstring",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="master_data.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project String Detail",
                "verbose_name_plural": "Project String Details",
                "ordering": ["workspace", "string", "dimension"],
                "indexes": [
                    models.Index(
                        fields=["string", "dimension"],
                        name="master_data_string__32e211_idx",
                    )
                ],
                "unique_together": {("workspace", "string", "dimension")},
            },
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["workspace", "project", "platform"],
                name="master_data_workspa_967fd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["workspace", "string_uuid"],
                name="master_data_workspa_a04ca4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["workspace", "parent_uuid"],
                name="master_data_workspa_9f6d22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectstring",
            index=models.Index(
                fields=["project", "platform", "field"],
                name="master_data_project_8bd7c1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectstring",
            unique_together={
                ("workspace", "project", "platform", "field", "parent", "value")
            },
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="projectactivity",
            index=models.Index(
                fields=["project", "-created"], name="master_data_project_d2f945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "slug"], name="master_data_workspa_2cd34b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "status"], name="master_data_workspa_d8c7ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "owner"], name="master_data_workspa_c06756_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "approval_status"],
                name="master_data_workspa_550d5a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("workspace", "slug")},
        ),
        migrations.AddIndex(
            model_name="platformassignment",
            index=models.Index(
                fields=["project", "platform"], name="master_data_project_08fff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformassignment",
            index=models.Index(
                fields=["workspace", "approval_status"],
                name="master_data_workspa_70b9bd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="platformassignment",
            unique_together={("project", "platform")},
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(
                fields=["project", "-timestamp"], name="master_data_project_db4330_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(
                fields=["platform_assignment", "-timestamp"],
                name="master_data_platfor_66142a_idx",
            ),
        ),
    ]
