# Generated by Django 4.2.20 on 2025-06-01 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import master_data.models.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0006_fix_related_name_conflicts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dimension",
            options={
                "ordering": ["name"],
                "verbose_name": "Dimension",
                "verbose_name_plural": "Dimensions",
            },
        ),
        migrations.AlterModelOptions(
            name="dimensionvalue",
            options={
                "ordering": ["dimension", "value"],
                "verbose_name": "Dimension Value",
                "verbose_name_plural": "Dimension Values",
            },
        ),
        migrations.AlterModelOptions(
            name="field",
            options={
                "ordering": ["platform", "field_level"],
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={
                "ordering": ["name"],
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-created"],
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
            },
        ),
        migrations.AlterModelOptions(
            name="workspace",
            options={
                "ordering": ["name"],
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
            },
        ),
        migrations.AlterField(
            model_name="dimension",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of what this dimension represents",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="name",
            field=models.CharField(
                help_text="Unique name for this dimension", max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent dimension if this is a sub-dimension",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_dimensions",
                to="master_data.dimension",
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Current status of this dimension",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="type",
            field=models.CharField(
                choices=[("list", "List"), ("text", "Free Text")],
                default="list",
                help_text="Type of dimension: list of values or free text",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of what this value represents",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="dimension",
            field=models.ForeignKey(
                help_text="The dimension this value belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimension_values",
                to="master_data.dimension",
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="label",
            field=models.CharField(
                help_text="Human-readable label for this value", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent value if this is a sub-value",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_dimension_values",
                to="master_data.dimensionvalue",
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="utm",
            field=models.CharField(
                help_text="UTM or tracking code for this value", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="valid_from",
            field=models.DateField(
                blank=True, help_text="Date from which this value is valid", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="valid_until",
            field=models.DateField(
                blank=True, help_text="Date until which this value is valid", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="value",
            field=models.CharField(
                help_text="The actual value (e.g., 'prod', 'dev')", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="field_level",
            field=models.SmallIntegerField(
                help_text="Hierarchical level of this field (1, 2, 3, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(
                help_text="Name of this field (e.g., 'environment', 'project')",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="next_field",
            field=models.ForeignKey(
                blank=True,
                help_text="Next field in the hierarchy sequence",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_fields",
                to="master_data.field",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this field belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="master_data.platform",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the icon to display for this platform",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(
                help_text="Human-readable name of the platform", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="platform_type",
            field=models.CharField(
                help_text="Type or category of this platform", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly identifier for this platform", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this submission",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="name",
            field=models.CharField(help_text="Name for this submission", max_length=30),
        ),
        migrations.AlterField(
            model_name="submission",
            name="rule",
            field=models.ForeignKey(
                help_text="The naming rule to apply for this submission",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="master_data.rule",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="selected_parent_string",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent string to base this submission on (if any)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_parent_string",
                to="master_data.string",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="starting_field",
            field=models.ForeignKey(
                help_text="The field to start the naming sequence from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_field",
                to="master_data.field",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="Current status of this submission",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=master_data.models.base.default_workspace_logo,
                help_text="Logo image for this workspace",
                null=True,
                upload_to="workspaces/logos/",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(
                help_text="Unique name for this workspace", max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Current status of this workspace",
                max_length=30,
            ),
        ),
    ]
