# Generated by Django 4.2.20 on 2025-06-01 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0007_improve_code_readability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rule",
            options={
                "ordering": ["platform", "name"],
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="ruledetail",
            options={
                "ordering": ["rule", "field", "dimension_order"],
                "verbose_name": "Rule Detail",
                "verbose_name_plural": "Rule Details",
            },
        ),
        migrations.AlterModelOptions(
            name="string",
            options={
                "ordering": ["field__field_level", "value"],
                "verbose_name": "String",
                "verbose_name_plural": "Strings",
            },
        ),
        migrations.AlterModelOptions(
            name="stringdetail",
            options={
                "ordering": ["string", "dimension"],
                "verbose_name": "String Detail",
                "verbose_name_plural": "String Details",
            },
        ),
        migrations.AddField(
            model_name="rule",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the default rule for the platform",
            ),
        ),
        migrations.AddField(
            model_name="ruledetail",
            name="is_required",
            field=models.BooleanField(
                default=True,
                help_text="Whether this dimension is required for string generation",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="generation_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Metadata about how this string was generated",
            ),
        ),
        migrations.AddField(
            model_name="string",
            name="is_auto_generated",
            field=models.BooleanField(
                default=False,
                help_text="Whether this string was automatically generated",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of what this rule generates",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="name",
            field=models.CharField(help_text="Name of this naming rule", max_length=50),
        ),
        migrations.AlterField(
            model_name="rule",
            name="platform",
            field=models.ForeignKey(
                help_text="Platform this rule applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="master_data.platform",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Current status of this rule",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="delimiter",
            field=models.CharField(
                blank=True,
                default="-",
                help_text="Character to separate this dimension from others",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="dimension",
            field=models.ForeignKey(
                help_text="Dimension this formatting applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_details",
                to="master_data.dimension",
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="dimension_order",
            field=models.SmallIntegerField(
                help_text="Order of this dimension in the naming sequence (1, 2, 3, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="field",
            field=models.ForeignKey(
                help_text="Field this formatting applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_details",
                to="master_data.field",
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="prefix",
            field=models.CharField(
                blank=True,
                help_text="Text to prepend to the dimension value",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="rule",
            field=models.ForeignKey(
                help_text="Rule this detail belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_details",
                to="master_data.rule",
            ),
        ),
        migrations.AlterField(
            model_name="ruledetail",
            name="suffix",
            field=models.CharField(
                blank=True,
                help_text="Text to append to the dimension value",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="field",
            field=models.ForeignKey(
                help_text="Field this string belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_strings",
                to="master_data.field",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent string in hierarchical naming structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_strings",
                to="master_data.string",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="parent_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of parent string for hierarchical linking",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="rule",
            field=models.ForeignKey(
                editable=False,
                help_text="Rule used to generate this string (auto-set from submission)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_strings",
                to="master_data.rule",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="string_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this string",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="submission",
            field=models.ForeignKey(
                help_text="Submission that generated this string",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_strings",
                to="master_data.submission",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="value",
            field=models.CharField(
                help_text="Generated string value following naming convention",
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="dimension",
            field=models.ForeignKey(
                help_text="Dimension this value represents",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="string_details",
                to="master_data.dimension",
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="dimension_value",
            field=models.ForeignKey(
                blank=True,
                help_text="Predefined dimension value (for list-type dimensions)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="string_details",
                to="master_data.dimensionvalue",
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="dimension_value_freetext",
            field=models.CharField(
                blank=True,
                help_text="Free text value (for text-type dimensions)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="string",
            field=models.ForeignKey(
                help_text="String this detail belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="string_details",
                to="master_data.string",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rule", unique_together={("platform", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="stringdetail", unique_together={("string", "dimension")},
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["platform", "status"], name="master_data_platfor_288f6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["is_default"], name="master_data_is_defa_1b8562_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["rule", "field", "dimension_order"],
                name="master_data_rule_id_0753aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["rule", "field"], name="master_data_rule_id_3e6327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["string_uuid"], name="master_data_string__f6b20b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(fields=["value"], name="master_data_value_62f6c7_idx"),
        ),
    ]
