# Generated by Django 4.1 on 2023-10-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_convention'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rule',
            name='convention',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='master_data.convention'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('convention', 'name')},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='workspace',
        ),
    ]
