# Generated by Django 4.2.20 on 2025-06-02 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0008_add_string_generation_logic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="string",
            name="string_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for this string",
                unique=True,
            ),
        ),
    ]
