# Generated by Django 4.1 on 2023-10-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_alter_rule_unique_together_rule_convention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='master_data.field'),
            preserve_default=False,
        ),
    ]
