# Generated by Django 4.2.7 on 2025-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0009_remove_platform_assignment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="approvalhistory",
            name="master_data_platfor_66142a_idx",
        ),
        migrations.AddField(
            model_name="project",
            name="platforms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Platforms assigned to this project",
                related_name="projects",
                to="master_data.platform",
            ),
        ),
        migrations.AlterField(
            model_name="projectactivity",
            name="type",
            field=models.CharField(
                choices=[
                    ("project_created", "Project Created"),
                    ("member_assigned", "Member Assigned"),
                    ("member_unassigned", "Member Unassigned"),
                    ("strings_generated", "Strings Generated"),
                    ("status_changed", "Status Changed"),
                    ("project_updated", "Project Updated"),
                    ("submitted_for_approval", "Submitted for Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                help_text="Type of activity",
                max_length=50,
            ),
        ),
    ]
