# Generated by Django 4.1 on 2023-10-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_rule_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='structure',
            name='convention',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.convention'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together={('convention', 'field', 'dimension_order')},
        ),
        migrations.RemoveField(
            model_name='structure',
            name='rule',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
