# Generated by Django 4.2.7 on 2025-11-09 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_add_project_platforms'),
    ]

    operations = [
        # Step 1: Rename the Field model to Entity
        migrations.RenameModel(
            old_name='Field',
            new_name='Entity',
        ),

        # Step 2: Rename field_level to entity_level on Entity model
        migrations.RenameField(
            model_name='entity',
            old_name='field_level',
            new_name='entity_level',
        ),

        # Step 3: Rename next_field to next_entity on Entity model
        migrations.RenameField(
            model_name='entity',
            old_name='next_field',
            new_name='next_entity',
        ),

        # Step 4: Rename field to entity on RuleDetail model
        migrations.RenameField(
            model_name='ruledetail',
            old_name='field',
            new_name='entity',
        ),

        # Step 5: Rename field to entity on String model
        migrations.RenameField(
            model_name='string',
            old_name='field',
            new_name='entity',
        ),

        # Step 6: Rename field to entity on ProjectString model
        migrations.RenameField(
            model_name='projectstring',
            old_name='field',
            new_name='entity',
        ),

        # Step 7: Rename field to entity on StringUpdateBatch model
        migrations.RenameField(
            model_name='stringupdatebatch',
            old_name='field',
            new_name='entity',
        ),

        # Step 8: Rename starting_field to starting_entity on Submission model
        migrations.RenameField(
            model_name='submission',
            old_name='starting_field',
            new_name='starting_entity',
        ),
    ]
