# Generated by Django 4.1 on 2023-10-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_alter_platform_unique_together_platform_convention_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='structure',
            name='convention',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='master_data.convention'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together={('convention', 'field', 'dimension_order')},
        ),
        migrations.RemoveField(
            model_name='platform',
            name='convention',
        ),
    ]
