# Generated by Django 4.1 on 2023-10-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_alter_platform_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='field_name',
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('platform', 'field_name', 'field_level')},
        ),
    ]
