# Generated by Django 4.1 on 2023-10-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_rename_name_field_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='delimeter_after_dimension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='delimeter_before_dimension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
