# Generated by Django 4.1 on 2023-10-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_alter_structure_delimeter_after_dimension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junkdimension',
            name='dimension_value_code',
        ),
    ]
