# Generated by Django 4.1 on 2024-02-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0016_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="string",
            name="convention",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strings",
                to="master_data.convention",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="string",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strings",
                to="master_data.field",
            ),
        ),
    ]
