# Generated by Django 4.1 on 2024-02-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0017_string_convention_alter_string_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field", old_name="field_name", new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="field", unique_together={("platform", "name", "field_level")},
        ),
    ]
