# Generated by Django 4.1 on 2024-03-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0018_rename_field_name_field_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="string", old_name="string_id", new_name="string_uuid",
        ),
        migrations.AddField(
            model_name="string",
            name="parent_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
