# Generated by Django 4.1 on 2024-03-10 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0019_rename_string_id_string_string_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ConventionPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.convention",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.platform",
                    ),
                ),
            ],
        ),
    ]
