# Generated by Django 3.2.5 on 2024-12-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_add_workspace_logo'),
        ('master_data', '0020_convention_status_conventionplatform'),
    ]

    operations = [
    ]
