# Generated by Django 3.2.5 on 2025-01-01 22:45

from django.db import migrations, models
import django.db.models.deletion
import master_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_merge_20241231_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='valid_from',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convention',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conventionplatform',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_platforms', to='master_data.convention'),
        ),
        migrations.AlterField(
            model_name='conventionplatform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_platforms', to='master_data.platform'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, default=master_data.models.default_workspace_logo, null=True, upload_to='workspaces/logos/'),
        ),
    ]
