# Generated by Django 3.2.5 on 2025-01-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_auto_20250101_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dimension_value_freetext', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='string_items', to='master_data.junkdimension')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_items', to='master_data.string')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_items', to='master_data.structure')),
            ],
        ),
    ]
