# Generated by Django 4.2 on 2025-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_stringitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_type',
            field=models.CharField(choices=[('list', 'List'), ('text', 'Free Text')], default='list', max_length=30),
        ),
    ]
