# Generated by Django 4.2 on 2025-03-23 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0024_dimension_status_alter_dimension_dimension_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, max_length=500, null=True)),
                ('dimension_value', models.CharField(max_length=30)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('dimension_value_label', models.CharField(max_length=50)),
                ('dimension_value_utm', models.CharField(max_length=30)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='master_data.dimension')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='master_data.dimensionvalue')),
            ],
            options={
                'unique_together': {('dimension', 'dimension_value')},
            },
        ),
        migrations.AlterField(
            model_name='stringitem',
            name='dimension_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='string_items', to='master_data.dimensionvalue'),
        ),
        migrations.DeleteModel(
            name='JunkDimension',
        ),
    ]
