# Generated by Django 4.2 on 2025-03-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_dimensionvalue_alter_stringitem_dimension_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='master_data.convention')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='master_data.field')),
            ],
        ),
        migrations.CreateModel(
            name='RuleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('delimeter', models.CharField(blank=True, max_length=1, null=True)),
                ('dimension_order', models.SmallIntegerField()),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_details', to='master_data.dimension')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_details', to='master_data.rule')),
            ],
            options={
                'unique_together': {('rule', 'dimension_order')},
            },
        ),
        migrations.CreateModel(
            name='StringDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dimension_value_freetext', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='string_details', to='master_data.dimensionvalue')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_details', to='master_data.rule')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='structure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='structure',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='field',
        ),
        migrations.RenameField(
            model_name='string',
            old_name='string_value',
            new_name='value',
        ),
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30),
        ),
        migrations.DeleteModel(
            name='StringItem',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
        migrations.AddField(
            model_name='stringdetail',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_details', to='master_data.string'),
        ),
    ]
