# Generated by Django 4.2 on 2025-03-23 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_rule_ruledetail_stringdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='status',
            field=models.CharField(choices=[(
                'active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(
                    blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('draft', 'Draft'), (
                    'approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='submissions', to='master_data.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='string',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='strings', to='master_data.submission'),
            preserve_default=False,
        ),
    ]
