# Generated by Django 4.2 on 2025-03-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_alter_convention_status_submission_string_submission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='convention',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='string',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='dimension',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='workspace',
        ),
    ]
