# Generated by Django 4.2 on 2025-03-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0028_alter_dimension_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='field',
        ),
        migrations.AddField(
            model_name='rule',
            name='platform',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='master_data.platform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruledetail',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rule_details', to='master_data.field'),
            preserve_default=False,
        ),
    ]
