# Generated by Django 4.2 on 2025-03-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_remove_rule_field_rule_platform_ruledetail_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruledetail',
            old_name='delimeter',
            new_name='delimiter',
        ),
    ]
