# Generated by Django 4.2 on 2025-03-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_rename_delimeter_ruledetail_delimiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventionplatform',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='conventionplatform',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='string',
            name='convention',
        ),
        migrations.DeleteModel(
            name='Convention',
        ),
        migrations.DeleteModel(
            name='ConventionPlatform',
        ),
    ]
