# Generated by Django 4.2 on 2025-03-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_remove_conventionplatform_convention_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruledetail',
            unique_together={('rule', 'field', 'dimension_order')},
        ),
    ]
