# Generated by Django 4.2 on 2025-04-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_alter_ruledetail_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
