# Generated by Django 4.2 on 2025-04-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0033_rule_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruledetail',
            unique_together={('rule', 'field', 'dimension', 'dimension_order')},
        ),
    ]
