# Generated by Django 4.2 on 2025-04-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0034_alter_ruledetail_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringdetail',
            name='rule',
        ),
        migrations.AddField(
            model_name='submission',
            name='rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='master_data.rule'),
            preserve_default=False,
        ),
    ]
