# Generated by Django 4.2 on 2025-04-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_remove_stringdetail_rule_submission_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringdetail',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='string_details', to='master_data.dimension'),
        ),
    ]
