# Generated by Django 4.2 on 2025-04-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0036_stringdetail_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringdetail',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_details', to='master_data.dimension'),
        ),
        migrations.AlterField(
            model_name='stringdetail',
            name='dimension_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_details', to='master_data.dimensionvalue'),
        ),
    ]
