# Generated by Django 4.2 on 2025-04-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0037_alter_stringdetail_dimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringdetail',
            name='dimension_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='string_details', to='master_data.dimensionvalue'),
        ),
    ]
