# Generated by Django 4.2 on 2025-04-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0038_alter_stringdetail_dimension_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='selected_parent_string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_parent_string', to='master_data.string'),
        ),
        migrations.AddField(
            model_name='submission',
            name='starting_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='starting_field', to='master_data.field'),
            preserve_default=False,
        ),
    ]
