# Generated by Django 4.2 on 2025-04-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0039_submission_selected_parent_string_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension',
            old_name='definition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dimension',
            old_name='dimension_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='dimensionvalue',
            old_name='definition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dimensionvalue',
            old_name='dimension_value_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='dimensionvalue',
            old_name='dimension_value',
            new_name='utm',
        ),
        migrations.RenameField(
            model_name='dimensionvalue',
            old_name='dimension_value_utm',
            new_name='value',
        ),
        migrations.AlterUniqueTogether(
            name='dimensionvalue',
            unique_together={('dimension', 'value')},
        ),
    ]
