# Generated by Django 4.2 on 2025-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0040_rename_definition_dimension_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='string',
            name='value',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
