# Generated by Django 4.2 on 2025-04-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0041_alter_string_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='rule',
            field=models.ForeignKey(default=15, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rule_strings', to='master_data.rule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='string',
            name='value',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='string',
            unique_together={('rule', 'field', 'value')},
        ),
    ]
