# Generated by Django 4.2.20 on 2025-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimension",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name (auto-generated)",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name (auto-generated)",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name (auto-generated)",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name (auto-generated)",
                unique=True,
            ),
        ),
    ]
