# Generated by Django 4.2.20 on 2025-06-07 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_add_slug_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dimension",
            options={
                "ordering": ["workspace", "name"],
                "verbose_name": "Dimension",
                "verbose_name_plural": "Dimensions",
            },
        ),
        migrations.AlterModelOptions(
            name="dimensionvalue",
            options={
                "ordering": ["workspace", "dimension", "value"],
                "verbose_name": "Dimension Value",
                "verbose_name_plural": "Dimension Values",
            },
        ),
        migrations.AlterModelOptions(
            name="field",
            options={
                "ordering": ["workspace", "platform", "field_level"],
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={
                "ordering": ["workspace", "name"],
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
            },
        ),
        migrations.AlterModelOptions(
            name="rule",
            options={
                "ordering": ["workspace", "platform", "name"],
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="ruledetail",
            options={
                "ordering": ["workspace", "rule", "field", "dimension_order"],
                "verbose_name": "Rule Detail",
                "verbose_name_plural": "Rule Details",
            },
        ),
        migrations.AlterModelOptions(
            name="string",
            options={
                "ordering": ["workspace", "field__field_level", "value"],
                "verbose_name": "String",
                "verbose_name_plural": "Strings",
            },
        ),
        migrations.AlterModelOptions(
            name="stringdetail",
            options={
                "ordering": ["workspace", "string", "dimension"],
                "verbose_name": "String Detail",
                "verbose_name_plural": "String Details",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["workspace", "-created"],
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
            },
        ),
        migrations.RemoveIndex(
            model_name="rule", name="master_data_platfor_288f6c_idx",
        ),
        migrations.RemoveIndex(
            model_name="rule", name="master_data_is_defa_1b8562_idx",
        ),
        migrations.RemoveIndex(
            model_name="ruledetail", name="master_data_rule_id_0753aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="string", name="master_data_rule_id_3e6327_idx",
        ),
        migrations.RemoveIndex(
            model_name="string", name="master_data_string__f6b20b_idx",
        ),
        migrations.RemoveIndex(
            model_name="string", name="master_data_value_62f6c7_idx",
        ),
        migrations.AlterUniqueTogether(
            name="dimensionvalue", unique_together=set(),),
        migrations.AlterUniqueTogether(name="field", unique_together=set(),),
        migrations.AlterUniqueTogether(name="rule", unique_together=set(),),
        migrations.AlterUniqueTogether(
            name="ruledetail", unique_together=set(),),
        migrations.AlterUniqueTogether(name="string", unique_together=set(),),
        migrations.AlterUniqueTogether(
            name="stringdetail", unique_together=set(),),
        migrations.AddField(
            model_name="dimension",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dimensionvalue",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="field",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ruledetail",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="string",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stringdetail",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dimension",
            name="name",
            field=models.CharField(
                help_text="Name for this dimension (unique per workspace)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dimension",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name (auto-generated)",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly identifier for this platform"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name (auto-generated)",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="string_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for this string (unique per workspace)",
            ),
        ),
        migrations.AlterField(
            model_name="stringdetail",
            name="dimension_value_freetext",
            field=models.CharField(
                blank=True,
                help_text="Free-text dimension value (for text-type dimensions)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of the name (auto-generated)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dimension", unique_together={("workspace", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dimensionvalue",
            unique_together={("workspace", "dimension", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="field",
            unique_together={("workspace", "platform", "name", "field_level")},
        ),
        migrations.AlterUniqueTogether(
            name="platform", unique_together={("workspace", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="rule", unique_together={("workspace", "platform", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="ruledetail",
            unique_together={
                ("workspace", "rule", "field", "dimension", "dimension_order")
            },
        ),
        migrations.AlterUniqueTogether(
            name="string", unique_together={("workspace", "rule", "field", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="stringdetail", unique_together={("workspace", "string", "dimension")},
        ),
        migrations.AlterUniqueTogether(
            name="submission", unique_together={("workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["workspace", "platform", "status"],
                name="master_data_workspa_a5ef98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["workspace", "is_default"],
                name="master_data_workspa_ad5e78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["workspace", "rule", "field"],
                name="master_data_workspa_f3369d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ruledetail",
            index=models.Index(
                fields=["workspace", "dimension"], name="master_data_workspa_9de020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "rule", "field"],
                name="master_data_workspa_d655d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "string_uuid"],
                name="master_data_workspa_acdcc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="string",
            index=models.Index(
                fields=["workspace", "value"], name="master_data_workspa_6947b4_idx"
            ),
        ),
    ]
