# Generated by Django 4.2.20 on 2025-06-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0005_recreate_platform_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dimension",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_dimensions",
                to="master_data.dimension",
            ),
        ),
        migrations.AlterField(
            model_name="dimensionvalue",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_dimension_values",
                to="master_data.dimensionvalue",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="next_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_fields",
                to="master_data.field",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_strings",
                to="master_data.field",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_strings",
                to="master_data.string",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_strings",
                to="master_data.submission",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="master_data.rule",
            ),
        ),
    ]
