# Generated by Django 4.2.20 on 2025-06-30 23:30

from django.db import migrations


def remove_workspace_fields_from_platform_field(apps, schema_editor):
    """
    Remove workspace_id columns from Platform and Field tables
    since these models should be workspace-agnostic.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Get the database introspection
        introspection = connection.introspection

        # Check Platform table
        try:
            existing_tables = introspection.table_names(cursor)

            if 'master_data_platform' in existing_tables:
                platform_columns = [col.name for col in introspection.get_table_description(
                    cursor, 'master_data_platform')]

                if 'workspace_id' in platform_columns:
                    print("Removing workspace_id from master_data_platform")
                    if connection.vendor == 'postgresql':
                        # Drop foreign key constraint first
                        cursor.execute("""
                            ALTER TABLE master_data_platform 
                            DROP CONSTRAINT IF EXISTS master_data_platform_workspace_id_fkey
                        """)
                        # Drop the column
                        cursor.execute("""
                            ALTER TABLE master_data_platform 
                            DROP COLUMN workspace_id
                        """)
                    elif connection.vendor == 'sqlite':
                        # SQLite doesn't support DROP COLUMN easily, so we'll recreate the table
                        cursor.execute("""
                            CREATE TABLE master_data_platform_new (
                                id INTEGER PRIMARY KEY AUTOINCREMENT,
                                created DATETIME NOT NULL,
                                last_updated DATETIME NOT NULL,
                                created_by_id BIGINT NULL,
                                platform_type VARCHAR(30) NOT NULL,
                                name VARCHAR(30) NOT NULL,
                                slug VARCHAR(50) NOT NULL,
                                icon_name VARCHAR(30) NULL,
                                FOREIGN KEY (created_by_id) REFERENCES auth_user(id)
                            )
                        """)

                        cursor.execute("""
                            INSERT INTO master_data_platform_new 
                            (id, created, last_updated, created_by_id, platform_type, name, slug, icon_name)
                            SELECT id, created, last_updated, created_by_id, platform_type, name, slug, icon_name
                            FROM master_data_platform
                        """)

                        cursor.execute("DROP TABLE master_data_platform")
                        cursor.execute(
                            "ALTER TABLE master_data_platform_new RENAME TO master_data_platform")

                        # Recreate indexes
                        cursor.execute(
                            "CREATE UNIQUE INDEX master_data_platform_slug_unique ON master_data_platform(slug)")
                else:
                    print("workspace_id column not found in master_data_platform")

        except Exception as e:
            print(f"Error removing workspace_id from platform: {e}")

        # Check Field table
        try:
            if 'master_data_field' in existing_tables:
                field_columns = [col.name for col in introspection.get_table_description(
                    cursor, 'master_data_field')]

                if 'workspace_id' in field_columns:
                    print("Removing workspace_id from master_data_field")
                    if connection.vendor == 'postgresql':
                        # Drop foreign key constraint first
                        cursor.execute("""
                            ALTER TABLE master_data_field 
                            DROP CONSTRAINT IF EXISTS master_data_field_workspace_id_fkey
                        """)
                        # Drop the column
                        cursor.execute("""
                            ALTER TABLE master_data_field 
                            DROP COLUMN workspace_id
                        """)
                    elif connection.vendor == 'sqlite':
                        # SQLite doesn't support DROP COLUMN easily, so we'll recreate the table
                        cursor.execute("""
                            CREATE TABLE master_data_field_new (
                                id INTEGER PRIMARY KEY AUTOINCREMENT,
                                created DATETIME NOT NULL,
                                last_updated DATETIME NOT NULL,
                                created_by_id BIGINT NULL,
                                platform_id BIGINT NOT NULL,
                                next_field_id BIGINT NULL,
                                name VARCHAR(30) NOT NULL,
                                field_level SMALLINT NOT NULL,
                                FOREIGN KEY (created_by_id) REFERENCES auth_user(id),
                                FOREIGN KEY (platform_id) REFERENCES master_data_platform(id),
                                FOREIGN KEY (next_field_id) REFERENCES master_data_field(id)
                            )
                        """)

                        cursor.execute("""
                            INSERT INTO master_data_field_new 
                            (id, created, last_updated, created_by_id, platform_id, next_field_id, name, field_level)
                            SELECT id, created, last_updated, created_by_id, platform_id, next_field_id, name, field_level
                            FROM master_data_field
                        """)

                        cursor.execute("DROP TABLE master_data_field")
                        cursor.execute(
                            "ALTER TABLE master_data_field_new RENAME TO master_data_field")

                        # Recreate indexes and constraints
                        cursor.execute("""
                            CREATE UNIQUE INDEX master_data_field_platform_name_level_unique 
                            ON master_data_field(platform_id, name, field_level)
                        """)
                else:
                    print("workspace_id column not found in master_data_field")

        except Exception as e:
            print(f"Error removing workspace_id from field: {e}")


def reverse_remove_workspace_fields(apps, schema_editor):
    """
    Reverse operation - add workspace_id columns back
    """
    # This would be complex to implement, so we'll leave it as a no-op
    # If needed, it would involve re-adding the columns and assigning default workspace
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_add_missing_workspace_fields'),
    ]

    operations = [
        migrations.RunPython(
            remove_workspace_fields_from_platform_field,
            reverse_remove_workspace_fields,
        ),
    ]
