# Generated by Django 4.2.17 on 2025-08-04 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("master_data", "0007_add_created_by_to_audit_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stringinheritanceupdate",
            options={
                "ordering": ["-applied_at"],
                "verbose_name": "String Inheritance Update",
                "verbose_name_plural": "String Inheritance Updates",
            },
        ),
        migrations.AlterModelOptions(
            name="stringmodification",
            options={
                "ordering": ["-modified_at"],
                "verbose_name": "String Modification",
                "verbose_name_plural": "String Modifications",
            },
        ),
        migrations.AlterModelOptions(
            name="stringupdatebatch",
            options={
                "ordering": ["-initiated_at"],
                "verbose_name": "String Update Batch",
                "verbose_name_plural": "String Update Batches",
            },
        ),
        migrations.RenameIndex(
            model_name="propagationerror",
            new_name="master_data_workspa_eca2f6_idx",
            old_name="master_data_propagat_workspace_error_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationerror",
            new_name="master_data_workspa_d988fe_idx",
            old_name="master_data_propagat_workspace_resolved_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationerror",
            new_name="master_data_job_id_ebf23d_idx",
            old_name="master_data_propagat_job_error_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationerror",
            new_name="master_data_created_1b222d_idx",
            old_name="master_data_propagat_error_created_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationjob",
            new_name="master_data_workspa_9e06aa_idx",
            old_name="master_data_propagat_workspace_status_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationjob",
            new_name="master_data_workspa_9f76b2_idx",
            old_name="master_data_propagat_workspace_user_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationjob",
            new_name="master_data_batch_i_1633f2_idx",
            old_name="master_data_propagat_batch_id_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationjob",
            new_name="master_data_created_5f07a9_idx",
            old_name="master_data_propagat_created_idx",
        ),
        migrations.RenameIndex(
            model_name="propagationsettings",
            new_name="master_data_workspa_2c1b07_idx",
            old_name="master_data_propagat_userworkspace_idx",
        ),
        migrations.AddField(
            model_name="propagationerror",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationjob",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propagationsettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="propagationerror",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="propagationjob",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="propagationsettings",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="string",
            name="version",
            field=models.IntegerField(
                default=1, help_text="Current version number for tracking modifications"
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="applied_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the inheritance update was applied"
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="child_string",
            field=models.ForeignKey(
                help_text="Child string that received inherited changes",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inheritance_received",
                to="master_data.string",
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="inherited_fields",
            field=models.JSONField(help_text="Fields that were inherited from parent"),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="parent_modification",
            field=models.ForeignKey(
                help_text="Parent modification that triggered this inheritance update",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inheritance_updates",
                to="master_data.stringmodification",
            ),
        ),
        migrations.AlterField(
            model_name="stringinheritanceupdate",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="batch_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of batch operation if part of batch",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("direct_edit", "Direct Edit"),
                    ("inheritance_update", "Inheritance Update"),
                    ("batch_update", "Batch Update"),
                    ("regeneration", "Regeneration"),
                ],
                help_text="Type of change that was made",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="field_updates",
            field=models.JSONField(
                help_text="JSON object containing field updates made"
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata about the modification",
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="modified_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this modification was made"
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="modified_by",
            field=models.ForeignKey(
                help_text="User who made this modification",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="original_values",
            field=models.JSONField(help_text="Original values before modification"),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent version that triggered this change",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_versions",
                to="master_data.stringmodification",
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="string",
            field=models.ForeignKey(
                help_text="String that was modified",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifications",
                to="master_data.string",
            ),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="string_value",
            field=models.TextField(help_text="String value after this modification"),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="version",
            field=models.IntegerField(help_text="Version number for this modification"),
        ),
        migrations.AlterField(
            model_name="stringmodification",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="backup_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of backup created before this operation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the batch operation completed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="failed_strings",
            field=models.IntegerField(
                default=0, help_text="Number of strings that failed to process"
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="field",
            field=models.ForeignKey(
                help_text="Field being updated in this batch",
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.field",
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="initiated_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the batch operation was started"
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="initiated_by",
            field=models.ForeignKey(
                help_text="User who initiated this batch operation",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata about the batch operation",
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="processed_strings",
            field=models.IntegerField(
                default=0, help_text="Number of strings successfully processed"
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="rule",
            field=models.ForeignKey(
                help_text="Rule being updated in this batch",
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.rule",
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the batch operation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="total_strings",
            field=models.IntegerField(help_text="Total number of strings to update"),
        ),
        migrations.AlterField(
            model_name="stringupdatebatch",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="master_data.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["parent_modification"], name="master_data_parent__216de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["child_string"], name="master_data_child_s_7bc012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringinheritanceupdate",
            index=models.Index(
                fields=["workspace", "applied_at"],
                name="master_data_workspa_f8d7dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["string", "version"], name="master_data_string__be55fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["batch_id"], name="master_data_batch_i_3b1f74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["modified_at"], name="master_data_modifie_389c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringmodification",
            index=models.Index(
                fields=["workspace", "string"], name="master_data_workspa_eea181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringupdatebatch",
            index=models.Index(
                fields=["workspace", "status"], name="master_data_workspa_a9e9e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stringupdatebatch",
            index=models.Index(
                fields=["initiated_by", "initiated_at"],
                name="master_data_initiat_8b7c81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stringupdatebatch",
            index=models.Index(
                fields=["rule", "field"], name="master_data_rule_id_8871b0_idx"
            ),
        ),
    ]
