# Generated by Django 4.2.20 on 2025-08-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0008_add_created_by_to_propagation_models"),
    ]

    operations = [
        migrations.RemoveField(model_name="submission", name="selected_parent_string",),
        migrations.AlterUniqueTogether(
            name="dimension",
            unique_together={("workspace", "slug"), ("workspace", "name")},
        ),
    ]
